// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AccountAddressDeleteSecurity struct {
	APIKey string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (o *AccountAddressDeleteSecurity) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

type AccountAddressDeleteRequest struct {
	// The publicly viewable identifier used to identify a merchant division.
	XPublishableKey string `header:"style=simple,explode=false,name=X-Publishable-Key"`
	// The ID of the address to delete
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *AccountAddressDeleteRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

func (o *AccountAddressDeleteRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// AccountAddressDelete422ApplicationJSON - An error has occured, e.g. the identifier is not associated with an existing Bolt account
type AccountAddressDelete422ApplicationJSON struct {
	// The type of error returned
	DotTag string `json:".tag"`
	// A human-readable error message, which might include information specific to
	// the request that was made.
	//
	Message string `json:"message"`
}

func (o *AccountAddressDelete422ApplicationJSON) GetDotTag() string {
	if o == nil {
		return ""
	}
	return o.DotTag
}

func (o *AccountAddressDelete422ApplicationJSON) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

type AccountAddressDeleteResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// An error has occured, e.g. the identifier is not associated with an existing Bolt account
	AccountAddressDelete422ApplicationJSONObject *AccountAddressDelete422ApplicationJSON
}

func (o *AccountAddressDeleteResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AccountAddressDeleteResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AccountAddressDeleteResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *AccountAddressDeleteResponse) GetAccountAddressDelete422ApplicationJSONObject() *AccountAddressDelete422ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.AccountAddressDelete422ApplicationJSONObject
}
