// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/bolt-alpha-spec/pkg/models/shared"
	"net/http"
)

type AccountAddPaymentMethodRequest struct {
	// The publicly viewable identifier used to identify a merchant division.
	XPublishableKey    string                    `header:"style=simple,explode=false,name=X-Publishable-Key"`
	PaymentMethodInput shared.PaymentMethodInput `request:"mediaType=application/json"`
}

func (o *AccountAddPaymentMethodRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

func (o *AccountAddPaymentMethodRequest) GetPaymentMethodInput() shared.PaymentMethodInput {
	if o == nil {
		return shared.PaymentMethodInput{}
	}
	return o.PaymentMethodInput
}

func (o *AccountAddPaymentMethodRequest) GetPaymentMethodInputCreditCard() *shared.PaymentMethodCreditCardInput {
	return o.GetPaymentMethodInput().PaymentMethodCreditCardInput
}

func (o *AccountAddPaymentMethodRequest) GetPaymentMethodInputPaypal() *shared.PaymentMethodPaypal {
	return o.GetPaymentMethodInput().PaymentMethodPaypal
}

type AccountAddPaymentMethodResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The payment method was successfully added
	PaymentMethod *shared.PaymentMethodOutput
}

func (o *AccountAddPaymentMethodResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AccountAddPaymentMethodResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AccountAddPaymentMethodResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *AccountAddPaymentMethodResponse) GetPaymentMethod() *shared.PaymentMethodOutput {
	if o == nil {
		return nil
	}
	return o.PaymentMethod
}

func (o *AccountAddPaymentMethodResponse) GetPaymentMethodCreditCard() *shared.PaymentMethodCreditCardOutput {
	if v := o.GetPaymentMethod(); v != nil {
		return v.PaymentMethodCreditCardOutput
	}
	return nil
}

func (o *AccountAddPaymentMethodResponse) GetPaymentMethodPaypal() *shared.PaymentMethodPaypalOutput {
	if v := o.GetPaymentMethod(); v != nil {
		return v.PaymentMethodPaypalOutput
	}
	return nil
}
