// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"errors"
	"github.com/speakeasy-sdks/bolt-alpha-spec/pkg/models/shared"
	"github.com/speakeasy-sdks/bolt-alpha-spec/pkg/utils"
	"net/http"
)

type AccountAddressEditSecurity struct {
	APIKey string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
	Oauth  string `security:"scheme,type=oauth2,name=Authorization"`
}

func (o *AccountAddressEditSecurity) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *AccountAddressEditSecurity) GetOauth() string {
	if o == nil {
		return ""
	}
	return o.Oauth
}

type AccountAddressEditRequest struct {
	// The publicly viewable identifier used to identify a merchant division.
	XPublishableKey string `header:"style=simple,explode=false,name=X-Publishable-Key"`
	// The ID of the address to edit
	ID                                                                    string                                                                       `pathParam:"style=simple,explode=false,name=id"`
	Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput shared.Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput `request:"mediaType=application/json"`
}

func (o *AccountAddressEditRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

func (o *AccountAddressEditRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *AccountAddressEditRequest) GetOneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput() shared.Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput {
	if o == nil {
		return shared.Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput{}
	}
	return o.Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput
}

type AccountAddressEdit400ApplicationJSON2 struct {
	// The type of error returned
	dotTag string `const:"invalid_region" json:".tag"`
	// A human-readable error message, which might include information specific to
	// the request that was made.
	//
	Message string `json:"message"`
}

func (a AccountAddressEdit400ApplicationJSON2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountAddressEdit400ApplicationJSON2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *AccountAddressEdit400ApplicationJSON2) GetDotTag() string {
	return "invalid_region"
}

func (o *AccountAddressEdit400ApplicationJSON2) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

type AccountAddressEdit400ApplicationJSON1 struct {
	// The type of error returned
	dotTag string `const:"invalid_postal_code" json:".tag"`
	// A human-readable error message, which might include information specific to
	// the request that was made.
	//
	Message string `json:"message"`
}

func (a AccountAddressEdit400ApplicationJSON1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountAddressEdit400ApplicationJSON1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *AccountAddressEdit400ApplicationJSON1) GetDotTag() string {
	return "invalid_postal_code"
}

func (o *AccountAddressEdit400ApplicationJSON1) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

type AccountAddressEdit400ApplicationJSONType string

const (
	AccountAddressEdit400ApplicationJSONTypeAccountAddressEdit400ApplicationJSON1 AccountAddressEdit400ApplicationJSONType = "accountAddressEdit_400ApplicationJSON_1"
	AccountAddressEdit400ApplicationJSONTypeAccountAddressEdit400ApplicationJSON2 AccountAddressEdit400ApplicationJSONType = "accountAddressEdit_400ApplicationJSON_2"
)

type AccountAddressEdit400ApplicationJSON struct {
	AccountAddressEdit400ApplicationJSON1 *AccountAddressEdit400ApplicationJSON1
	AccountAddressEdit400ApplicationJSON2 *AccountAddressEdit400ApplicationJSON2

	Type AccountAddressEdit400ApplicationJSONType
}

func CreateAccountAddressEdit400ApplicationJSONAccountAddressEdit400ApplicationJSON1(accountAddressEdit400ApplicationJSON1 AccountAddressEdit400ApplicationJSON1) AccountAddressEdit400ApplicationJSON {
	typ := AccountAddressEdit400ApplicationJSONTypeAccountAddressEdit400ApplicationJSON1

	return AccountAddressEdit400ApplicationJSON{
		AccountAddressEdit400ApplicationJSON1: &accountAddressEdit400ApplicationJSON1,
		Type:                                  typ,
	}
}

func CreateAccountAddressEdit400ApplicationJSONAccountAddressEdit400ApplicationJSON2(accountAddressEdit400ApplicationJSON2 AccountAddressEdit400ApplicationJSON2) AccountAddressEdit400ApplicationJSON {
	typ := AccountAddressEdit400ApplicationJSONTypeAccountAddressEdit400ApplicationJSON2

	return AccountAddressEdit400ApplicationJSON{
		AccountAddressEdit400ApplicationJSON2: &accountAddressEdit400ApplicationJSON2,
		Type:                                  typ,
	}
}

func (u *AccountAddressEdit400ApplicationJSON) UnmarshalJSON(data []byte) error {

	accountAddressEdit400ApplicationJSON1 := new(AccountAddressEdit400ApplicationJSON1)
	if err := utils.UnmarshalJSON(data, &accountAddressEdit400ApplicationJSON1, "", true, true); err == nil {
		u.AccountAddressEdit400ApplicationJSON1 = accountAddressEdit400ApplicationJSON1
		u.Type = AccountAddressEdit400ApplicationJSONTypeAccountAddressEdit400ApplicationJSON1
		return nil
	}

	accountAddressEdit400ApplicationJSON2 := new(AccountAddressEdit400ApplicationJSON2)
	if err := utils.UnmarshalJSON(data, &accountAddressEdit400ApplicationJSON2, "", true, true); err == nil {
		u.AccountAddressEdit400ApplicationJSON2 = accountAddressEdit400ApplicationJSON2
		u.Type = AccountAddressEdit400ApplicationJSONTypeAccountAddressEdit400ApplicationJSON2
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u AccountAddressEdit400ApplicationJSON) MarshalJSON() ([]byte, error) {
	if u.AccountAddressEdit400ApplicationJSON1 != nil {
		return utils.MarshalJSON(u.AccountAddressEdit400ApplicationJSON1, "", true)
	}

	if u.AccountAddressEdit400ApplicationJSON2 != nil {
		return utils.MarshalJSON(u.AccountAddressEdit400ApplicationJSON2, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

type AccountAddressEditResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The request is missing required fields, or its fields have invalid values
	AccountAddressEdit400ApplicationJSONOneOf *AccountAddressEdit400ApplicationJSON
	// The address was successfully edited
	Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema *shared.Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema
}

func (o *AccountAddressEditResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AccountAddressEditResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AccountAddressEditResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *AccountAddressEditResponse) GetAccountAddressEdit400ApplicationJSONOneOf() *AccountAddressEdit400ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.AccountAddressEdit400ApplicationJSONOneOf
}

func (o *AccountAddressEditResponse) GetOneaccount1addressesPostRequestBodyContentApplication1jsonSchema() *shared.Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema {
	if o == nil {
		return nil
	}
	return o.Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema
}
