// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/bolt-alpha-spec/pkg/models/shared"
	"net/http"
)

type AccountGetSecurity struct {
	APIKey string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
	Oauth  string `security:"scheme,type=oauth2,name=Authorization"`
}

func (o *AccountGetSecurity) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *AccountGetSecurity) GetOauth() string {
	if o == nil {
		return ""
	}
	return o.Oauth
}

type AccountGetRequest struct {
	// The publicly viewable identifier used to identify a merchant division.
	XPublishableKey string `header:"style=simple,explode=false,name=X-Publishable-Key"`
}

func (o *AccountGetRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

type AccountGet200ApplicationJSONProfile struct {
	// An email address.
	Email *string `json:"email,omitempty"`
	// The given name of the person associated with this record.
	FirstName *string `json:"first_name,omitempty"`
	// The last name of the person associated with this record.
	LastName *string `json:"last_name,omitempty"`
	// A phone number following E164 standards, in its globalized format, i.e. prepended with a plus sign.
	Phone *string `json:"phone,omitempty"`
}

func (o *AccountGet200ApplicationJSONProfile) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *AccountGet200ApplicationJSONProfile) GetFirstName() *string {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *AccountGet200ApplicationJSONProfile) GetLastName() *string {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *AccountGet200ApplicationJSONProfile) GetPhone() *string {
	if o == nil {
		return nil
	}
	return o.Phone
}

// AccountGet200ApplicationJSON - The account details were successfully retrieved
type AccountGet200ApplicationJSON struct {
	Addresses      []shared.Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema            `json:"addresses"`
	PaymentMethods []shared.Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaOutput `json:"payment_methods"`
	Profile        *AccountGet200ApplicationJSONProfile                                                 `json:"profile,omitempty"`
}

func (o *AccountGet200ApplicationJSON) GetAddresses() []shared.Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema {
	if o == nil {
		return []shared.Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema{}
	}
	return o.Addresses
}

func (o *AccountGet200ApplicationJSON) GetPaymentMethods() []shared.Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaOutput {
	if o == nil {
		return []shared.Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaOutput{}
	}
	return o.PaymentMethods
}

func (o *AccountGet200ApplicationJSON) GetProfile() *AccountGet200ApplicationJSONProfile {
	if o == nil {
		return nil
	}
	return o.Profile
}

type AccountGetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// The account details were successfully retrieved
	AccountGet200ApplicationJSONObject *AccountGet200ApplicationJSON
}

func (o *AccountGetResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *AccountGetResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *AccountGetResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *AccountGetResponse) GetAccountGet200ApplicationJSONObject() *AccountGet200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.AccountGet200ApplicationJSONObject
}
