// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"errors"
	"github.com/speakeasy-sdks/bolt-alpha-spec/pkg/models/shared"
	"github.com/speakeasy-sdks/bolt-alpha-spec/pkg/utils"
	"net/http"
)

type GuestPaymentsInitializeRequestBodyPaymentMethod1 struct {
	dotTag string `const:"paypal" json:".tag"`
	// Redirect URL for canceled PayPal transaction.
	Cancel string `json:"cancel"`
	// Redirect URL for successful PayPal transaction.
	Success string `json:"success"`
}

func (g GuestPaymentsInitializeRequestBodyPaymentMethod1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GuestPaymentsInitializeRequestBodyPaymentMethod1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, true); err != nil {
		return err
	}
	return nil
}

func (o *GuestPaymentsInitializeRequestBodyPaymentMethod1) GetDotTag() string {
	return "paypal"
}

func (o *GuestPaymentsInitializeRequestBodyPaymentMethod1) GetCancel() string {
	if o == nil {
		return ""
	}
	return o.Cancel
}

func (o *GuestPaymentsInitializeRequestBodyPaymentMethod1) GetSuccess() string {
	if o == nil {
		return ""
	}
	return o.Success
}

type GuestPaymentsInitializeRequestBodyPaymentMethodType string

const (
	GuestPaymentsInitializeRequestBodyPaymentMethodTypeGuestPaymentsInitializeRequestBodyPaymentMethod1 GuestPaymentsInitializeRequestBodyPaymentMethodType = "guestPaymentsInitialize_requestBody_payment_method_1"
)

type GuestPaymentsInitializeRequestBodyPaymentMethod struct {
	GuestPaymentsInitializeRequestBodyPaymentMethod1 *GuestPaymentsInitializeRequestBodyPaymentMethod1

	Type GuestPaymentsInitializeRequestBodyPaymentMethodType
}

func CreateGuestPaymentsInitializeRequestBodyPaymentMethodGuestPaymentsInitializeRequestBodyPaymentMethod1(guestPaymentsInitializeRequestBodyPaymentMethod1 GuestPaymentsInitializeRequestBodyPaymentMethod1) GuestPaymentsInitializeRequestBodyPaymentMethod {
	typ := GuestPaymentsInitializeRequestBodyPaymentMethodTypeGuestPaymentsInitializeRequestBodyPaymentMethod1

	return GuestPaymentsInitializeRequestBodyPaymentMethod{
		GuestPaymentsInitializeRequestBodyPaymentMethod1: &guestPaymentsInitializeRequestBodyPaymentMethod1,
		Type: typ,
	}
}

func (u *GuestPaymentsInitializeRequestBodyPaymentMethod) UnmarshalJSON(data []byte) error {

	guestPaymentsInitializeRequestBodyPaymentMethod1 := new(GuestPaymentsInitializeRequestBodyPaymentMethod1)
	if err := utils.UnmarshalJSON(data, &guestPaymentsInitializeRequestBodyPaymentMethod1, "", true, true); err == nil {
		u.GuestPaymentsInitializeRequestBodyPaymentMethod1 = guestPaymentsInitializeRequestBodyPaymentMethod1
		u.Type = GuestPaymentsInitializeRequestBodyPaymentMethodTypeGuestPaymentsInitializeRequestBodyPaymentMethod1
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u GuestPaymentsInitializeRequestBodyPaymentMethod) MarshalJSON() ([]byte, error) {
	if u.GuestPaymentsInitializeRequestBodyPaymentMethod1 != nil {
		return utils.MarshalJSON(u.GuestPaymentsInitializeRequestBodyPaymentMethod1, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

type GuestPaymentsInitializeRequestBody struct {
	Cart          shared.OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCart `json:"cart"`
	PaymentMethod GuestPaymentsInitializeRequestBodyPaymentMethod                              `json:"payment_method"`
}

func (o *GuestPaymentsInitializeRequestBody) GetCart() shared.OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCart {
	if o == nil {
		return shared.OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCart{}
	}
	return o.Cart
}

func (o *GuestPaymentsInitializeRequestBody) GetPaymentMethod() GuestPaymentsInitializeRequestBodyPaymentMethod {
	if o == nil {
		return GuestPaymentsInitializeRequestBodyPaymentMethod{}
	}
	return o.PaymentMethod
}

type GuestPaymentsInitializeRequest struct {
	RequestBody GuestPaymentsInitializeRequestBody `request:"mediaType=application/json"`
	// The publicly viewable identifier used to identify a merchant division.
	XPublishableKey string `header:"style=simple,explode=false,name=X-Publishable-Key"`
}

func (o *GuestPaymentsInitializeRequest) GetRequestBody() GuestPaymentsInitializeRequestBody {
	if o == nil {
		return GuestPaymentsInitializeRequestBody{}
	}
	return o.RequestBody
}

func (o *GuestPaymentsInitializeRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

type GuestPaymentsInitializeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Payment token retrieved
	OnepaymentsPostResponses200ContentApplication1jsonSchema *shared.OnepaymentsPostResponses200ContentApplication1jsonSchema
}

func (o *GuestPaymentsInitializeResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GuestPaymentsInitializeResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GuestPaymentsInitializeResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GuestPaymentsInitializeResponse) GetOnepaymentsPostResponses200ContentApplication1jsonSchema() *shared.OnepaymentsPostResponses200ContentApplication1jsonSchema {
	if o == nil {
		return nil
	}
	return o.OnepaymentsPostResponses200ContentApplication1jsonSchema
}
