// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/bolt-alpha-spec/pkg/models/shared"
	"net/http"
)

type GuestPaymentsInitializeSecurity struct {
	APIKey string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (o *GuestPaymentsInitializeSecurity) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

type GuestPaymentsInitializeRequestBodyPaymentMethodTag string

const (
	GuestPaymentsInitializeRequestBodyPaymentMethodTagPaypal GuestPaymentsInitializeRequestBodyPaymentMethodTag = "paypal"
)

func (e GuestPaymentsInitializeRequestBodyPaymentMethodTag) ToPointer() *GuestPaymentsInitializeRequestBodyPaymentMethodTag {
	return &e
}

func (e *GuestPaymentsInitializeRequestBodyPaymentMethodTag) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "paypal":
		*e = GuestPaymentsInitializeRequestBodyPaymentMethodTag(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GuestPaymentsInitializeRequestBodyPaymentMethodTag: %v", v)
	}
}

type GuestPaymentsInitializeRequestBodyPaymentMethod struct {
	DotTag GuestPaymentsInitializeRequestBodyPaymentMethodTag `json:".tag"`
	// Redirect URL for canceled PayPal transaction.
	Cancel string `json:"cancel"`
	// Redirect URL for successful PayPal transaction.
	Success string `json:"success"`
}

func (o *GuestPaymentsInitializeRequestBodyPaymentMethod) GetDotTag() GuestPaymentsInitializeRequestBodyPaymentMethodTag {
	if o == nil {
		return GuestPaymentsInitializeRequestBodyPaymentMethodTag("")
	}
	return o.DotTag
}

func (o *GuestPaymentsInitializeRequestBodyPaymentMethod) GetCancel() string {
	if o == nil {
		return ""
	}
	return o.Cancel
}

func (o *GuestPaymentsInitializeRequestBodyPaymentMethod) GetSuccess() string {
	if o == nil {
		return ""
	}
	return o.Success
}

type GuestPaymentsInitializeRequestBody struct {
	Cart          shared.OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCart `json:"cart"`
	PaymentMethod GuestPaymentsInitializeRequestBodyPaymentMethod                              `json:"payment_method"`
}

func (o *GuestPaymentsInitializeRequestBody) GetCart() shared.OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCart {
	if o == nil {
		return shared.OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCart{}
	}
	return o.Cart
}

func (o *GuestPaymentsInitializeRequestBody) GetPaymentMethod() GuestPaymentsInitializeRequestBodyPaymentMethod {
	if o == nil {
		return GuestPaymentsInitializeRequestBodyPaymentMethod{}
	}
	return o.PaymentMethod
}

type GuestPaymentsInitializeRequest struct {
	RequestBody GuestPaymentsInitializeRequestBody `request:"mediaType=application/json"`
	// The publicly viewable identifier used to identify a merchant division.
	XPublishableKey string `header:"style=simple,explode=false,name=X-Publishable-Key"`
}

func (o *GuestPaymentsInitializeRequest) GetRequestBody() GuestPaymentsInitializeRequestBody {
	if o == nil {
		return GuestPaymentsInitializeRequestBody{}
	}
	return o.RequestBody
}

func (o *GuestPaymentsInitializeRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

type GuestPaymentsInitializeResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Payment token retrieved
	OnepaymentsPostResponses200ContentApplication1jsonSchema *shared.OnepaymentsPostResponses200ContentApplication1jsonSchema
}

func (o *GuestPaymentsInitializeResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GuestPaymentsInitializeResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GuestPaymentsInitializeResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GuestPaymentsInitializeResponse) GetOnepaymentsPostResponses200ContentApplication1jsonSchema() *shared.OnepaymentsPostResponses200ContentApplication1jsonSchema {
	if o == nil {
		return nil
	}
	return o.OnepaymentsPostResponses200ContentApplication1jsonSchema
}
