// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/bolt-alpha-spec/pkg/models/shared"
	"github.com/speakeasy-sdks/bolt-alpha-spec/pkg/utils"
	"net/http"
)

type GuestPaymentsInitializeRequestBodyPaymentMethod struct {
	dotTag string `const:"paypal" json:".tag"`
	// Redirect URL for canceled PayPal transaction.
	Cancel string `json:"cancel"`
	// Redirect URL for successful PayPal transaction.
	Success string `json:"success"`
}

func (g GuestPaymentsInitializeRequestBodyPaymentMethod) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GuestPaymentsInitializeRequestBodyPaymentMethod) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GuestPaymentsInitializeRequestBodyPaymentMethod) GetDotTag() string {
	return "paypal"
}

func (o *GuestPaymentsInitializeRequestBodyPaymentMethod) GetCancel() string {
	if o == nil {
		return ""
	}
	return o.Cancel
}

func (o *GuestPaymentsInitializeRequestBodyPaymentMethod) GetSuccess() string {
	if o == nil {
		return ""
	}
	return o.Success
}

type GuestPaymentsInitializeRequestBody struct {
	Cart          shared.OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCart `json:"cart"`
	PaymentMethod GuestPaymentsInitializeRequestBodyPaymentMethod                              `json:"payment_method"`
}

func (o *GuestPaymentsInitializeRequestBody) GetCart() shared.OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCart {
	if o == nil {
		return shared.OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCart{}
	}
	return o.Cart
}

func (o *GuestPaymentsInitializeRequestBody) GetPaymentMethod() GuestPaymentsInitializeRequestBodyPaymentMethod {
	if o == nil {
		return GuestPaymentsInitializeRequestBodyPaymentMethod{}
	}
	return o.PaymentMethod
}

type GuestPaymentsInitializeRequest struct {
	RequestBody GuestPaymentsInitializeRequestBody `request:"mediaType=application/json"`
	// The publicly viewable identifier used to identify a merchant division.
	XPublishableKey string `header:"style=simple,explode=false,name=X-Publishable-Key"`
}

func (o *GuestPaymentsInitializeRequest) GetRequestBody() GuestPaymentsInitializeRequestBody {
	if o == nil {
		return GuestPaymentsInitializeRequestBody{}
	}
	return o.RequestBody
}

func (o *GuestPaymentsInitializeRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

type GuestPaymentsInitializeResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Payment token retrieved
	OnepaymentsPostResponses200ContentApplication1jsonSchema *shared.OnepaymentsPostResponses200ContentApplication1jsonSchema
}

func (o *GuestPaymentsInitializeResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GuestPaymentsInitializeResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GuestPaymentsInitializeResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GuestPaymentsInitializeResponse) GetOnepaymentsPostResponses200ContentApplication1jsonSchema() *shared.OnepaymentsPostResponses200ContentApplication1jsonSchema {
	if o == nil {
		return nil
	}
	return o.OnepaymentsPostResponses200ContentApplication1jsonSchema
}
