// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/bolt-alpha-spec/pkg/models/shared"
	"net/http"
)

type GuestPaymentsActionSecurity struct {
	APIKey string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (o *GuestPaymentsActionSecurity) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

type GuestPaymentsActionRequest struct {
	// The publicly viewable identifier used to identify a merchant division.
	XPublishableKey string `header:"style=simple,explode=false,name=X-Publishable-Key"`
	// The ID of the guest payment to operate on
	ID                   string                      `pathParam:"style=simple,explode=false,name=id"`
	PaymentActionRequest shared.PaymentActionRequest `request:"mediaType=application/json"`
}

func (o *GuestPaymentsActionRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

func (o *GuestPaymentsActionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GuestPaymentsActionRequest) GetPaymentActionRequest() shared.PaymentActionRequest {
	if o == nil {
		return shared.PaymentActionRequest{}
	}
	return o.PaymentActionRequest
}

type GuestPaymentsActionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The action was successfully applied to the pending guest payment
	PaymentResponse *shared.PaymentResponse
}

func (o *GuestPaymentsActionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GuestPaymentsActionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GuestPaymentsActionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GuestPaymentsActionResponse) GetPaymentResponse() *shared.PaymentResponse {
	if o == nil {
		return nil
	}
	return o.PaymentResponse
}
