// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/bolt-alpha-spec/pkg/models/shared"
	"net/http"
)

type TestingAccountCreateSecurity struct {
	APIKey string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (o *TestingAccountCreateSecurity) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

type TestingAccountCreateRequest struct {
	// The publicly viewable identifier used to identify a merchant division.
	XPublishableKey              string                              `header:"style=simple,explode=false,name=X-Publishable-Key"`
	AccountTestCreationDataInput shared.AccountTestCreationDataInput `request:"mediaType=application/json"`
}

func (o *TestingAccountCreateRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

func (o *TestingAccountCreateRequest) GetAccountTestCreationDataInput() shared.AccountTestCreationDataInput {
	if o == nil {
		return shared.AccountTestCreationDataInput{}
	}
	return o.AccountTestCreationDataInput
}

type TestingAccountCreateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The account was successfully created
	AccountTestCreationData *shared.AccountTestCreationDataOutput
}

func (o *TestingAccountCreateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TestingAccountCreateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TestingAccountCreateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *TestingAccountCreateResponse) GetAccountTestCreationData() *shared.AccountTestCreationDataOutput {
	if o == nil {
		return nil
	}
	return o.AccountTestCreationData
}
