// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/bolt-alpha-spec/pkg/models/shared"
	"net/http"
)

type WebhooksGetRequest struct {
	// The ID of the webhook whose information to retrieve
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *WebhooksGetRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// WebhooksGet422ApplicationJSON - An error has occured, e.g. the identifier is not associated with an existing Bolt account
type WebhooksGet422ApplicationJSON struct {
	// The type of error returned
	DotTag string `json:".tag"`
	// A human-readable error message, which might include information specific to
	// the request that was made.
	//
	Message string `json:"message"`
}

func (o *WebhooksGet422ApplicationJSON) GetDotTag() string {
	if o == nil {
		return ""
	}
	return o.DotTag
}

func (o *WebhooksGet422ApplicationJSON) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

type WebhooksGetResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// An error has occured, e.g. the identifier is not associated with an existing Bolt account
	WebhooksGet422ApplicationJSONObject *WebhooksGet422ApplicationJSON
	// Webhook information has been retrieved
	OnewebhooksPutRequestBodyContentApplication1jsonSchema *shared.OnewebhooksPutRequestBodyContentApplication1jsonSchema
}

func (o *WebhooksGetResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *WebhooksGetResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *WebhooksGetResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *WebhooksGetResponse) GetWebhooksGet422ApplicationJSONObject() *WebhooksGet422ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.WebhooksGet422ApplicationJSONObject
}

func (o *WebhooksGetResponse) GetOnewebhooksPutRequestBodyContentApplication1jsonSchema() *shared.OnewebhooksPutRequestBodyContentApplication1jsonSchema {
	if o == nil {
		return nil
	}
	return o.OnewebhooksPutRequestBodyContentApplication1jsonSchema
}
