// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// AccountAddPaymentMethod4XXApplicationJSON - The payment method is invalid and cannot be added, or some other error has occurred
type AccountAddPaymentMethod4XXApplicationJSON struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &AccountAddPaymentMethod4XXApplicationJSON{}

func (e *AccountAddPaymentMethod4XXApplicationJSON) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
