// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// AccountAddressCreate4XXApplicationJSON - The address is invalid and cannot be added, or some other error has occurred
type AccountAddressCreate4XXApplicationJSON struct {
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &AccountAddressCreate4XXApplicationJSON{}

func (e *AccountAddressCreate4XXApplicationJSON) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
