// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Account struct {
	// A list of addresses associated with this account.
	Addresses []AddressListing `json:"addresses"`
	// A list of payment methods associated with this account.
	PaymentMethods []PaymentMethodOutput `json:"payment_methods"`
	Profile        *Profile              `json:"profile,omitempty"`
}

func (o *Account) GetAddresses() []AddressListing {
	if o == nil {
		return []AddressListing{}
	}
	return o.Addresses
}

func (o *Account) GetPaymentMethods() []PaymentMethodOutput {
	if o == nil {
		return []PaymentMethodOutput{}
	}
	return o.PaymentMethods
}

func (o *Account) GetProfile() *Profile {
	if o == nil {
		return nil
	}
	return o.Profile
}
