// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AddressID - The Address object is used for shipping, and physical store address use cases.
type AddressID struct {
	// The type of address reference
	DotTag string `json:".tag"`
	// The address's ID
	ID string `json:"id"`
}

func (o *AddressID) GetDotTag() string {
	if o == nil {
		return ""
	}
	return o.DotTag
}

func (o *AddressID) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
