// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AddressExplicitInput - The Address object is used for shipping, and physical store address use cases.
type AddressExplicitInput struct {
	// The type of address reference
	DotTag         string  `json:".tag"`
	Company        *string `json:"company,omitempty"`
	CountryCode    string  `json:"country_code"`
	Email          *string `json:"email,omitempty"`
	FirstName      string  `json:"first_name"`
	LastName       string  `json:"last_name"`
	Locality       string  `json:"locality"`
	Phone          *string `json:"phone,omitempty"`
	PostalCode     string  `json:"postal_code"`
	Region         *string `json:"region,omitempty"`
	StreetAddress1 string  `json:"street_address1"`
	StreetAddress2 *string `json:"street_address2,omitempty"`
}

func (o *AddressExplicitInput) GetDotTag() string {
	if o == nil {
		return ""
	}
	return o.DotTag
}

func (o *AddressExplicitInput) GetCompany() *string {
	if o == nil {
		return nil
	}
	return o.Company
}

func (o *AddressExplicitInput) GetCountryCode() string {
	if o == nil {
		return ""
	}
	return o.CountryCode
}

func (o *AddressExplicitInput) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *AddressExplicitInput) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *AddressExplicitInput) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *AddressExplicitInput) GetLocality() string {
	if o == nil {
		return ""
	}
	return o.Locality
}

func (o *AddressExplicitInput) GetPhone() *string {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *AddressExplicitInput) GetPostalCode() string {
	if o == nil {
		return ""
	}
	return o.PostalCode
}

func (o *AddressExplicitInput) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *AddressExplicitInput) GetStreetAddress1() string {
	if o == nil {
		return ""
	}
	return o.StreetAddress1
}

func (o *AddressExplicitInput) GetStreetAddress2() *string {
	if o == nil {
		return nil
	}
	return o.StreetAddress2
}
