// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/speakeasy-sdks/bolt-alpha-spec/pkg/utils"
)

// AddressReferenceAddressReferenceExplicitTag - The type of address reference
type AddressReferenceAddressReferenceExplicitTag string

const (
	AddressReferenceAddressReferenceExplicitTagExplicit AddressReferenceAddressReferenceExplicitTag = "explicit"
)

func (e AddressReferenceAddressReferenceExplicitTag) ToPointer() *AddressReferenceAddressReferenceExplicitTag {
	return &e
}

func (e *AddressReferenceAddressReferenceExplicitTag) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "explicit":
		*e = AddressReferenceAddressReferenceExplicitTag(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AddressReferenceAddressReferenceExplicitTag: %v", v)
	}
}

// AddressReferenceAddressReferenceExplicitCountryCode - The country (in its ISO 3166 alpha-2 format) associated with this address.
type AddressReferenceAddressReferenceExplicitCountryCode string

const (
	AddressReferenceAddressReferenceExplicitCountryCodeAf AddressReferenceAddressReferenceExplicitCountryCode = "AF"
	AddressReferenceAddressReferenceExplicitCountryCodeAx AddressReferenceAddressReferenceExplicitCountryCode = "AX"
	AddressReferenceAddressReferenceExplicitCountryCodeAl AddressReferenceAddressReferenceExplicitCountryCode = "AL"
	AddressReferenceAddressReferenceExplicitCountryCodeDz AddressReferenceAddressReferenceExplicitCountryCode = "DZ"
	AddressReferenceAddressReferenceExplicitCountryCodeAs AddressReferenceAddressReferenceExplicitCountryCode = "AS"
	AddressReferenceAddressReferenceExplicitCountryCodeAd AddressReferenceAddressReferenceExplicitCountryCode = "AD"
	AddressReferenceAddressReferenceExplicitCountryCodeAo AddressReferenceAddressReferenceExplicitCountryCode = "AO"
	AddressReferenceAddressReferenceExplicitCountryCodeAi AddressReferenceAddressReferenceExplicitCountryCode = "AI"
	AddressReferenceAddressReferenceExplicitCountryCodeAq AddressReferenceAddressReferenceExplicitCountryCode = "AQ"
	AddressReferenceAddressReferenceExplicitCountryCodeAg AddressReferenceAddressReferenceExplicitCountryCode = "AG"
	AddressReferenceAddressReferenceExplicitCountryCodeAr AddressReferenceAddressReferenceExplicitCountryCode = "AR"
	AddressReferenceAddressReferenceExplicitCountryCodeAm AddressReferenceAddressReferenceExplicitCountryCode = "AM"
	AddressReferenceAddressReferenceExplicitCountryCodeAw AddressReferenceAddressReferenceExplicitCountryCode = "AW"
	AddressReferenceAddressReferenceExplicitCountryCodeAu AddressReferenceAddressReferenceExplicitCountryCode = "AU"
	AddressReferenceAddressReferenceExplicitCountryCodeAt AddressReferenceAddressReferenceExplicitCountryCode = "AT"
	AddressReferenceAddressReferenceExplicitCountryCodeAz AddressReferenceAddressReferenceExplicitCountryCode = "AZ"
	AddressReferenceAddressReferenceExplicitCountryCodeBh AddressReferenceAddressReferenceExplicitCountryCode = "BH"
	AddressReferenceAddressReferenceExplicitCountryCodeBs AddressReferenceAddressReferenceExplicitCountryCode = "BS"
	AddressReferenceAddressReferenceExplicitCountryCodeBd AddressReferenceAddressReferenceExplicitCountryCode = "BD"
	AddressReferenceAddressReferenceExplicitCountryCodeBb AddressReferenceAddressReferenceExplicitCountryCode = "BB"
	AddressReferenceAddressReferenceExplicitCountryCodeBy AddressReferenceAddressReferenceExplicitCountryCode = "BY"
	AddressReferenceAddressReferenceExplicitCountryCodeBe AddressReferenceAddressReferenceExplicitCountryCode = "BE"
	AddressReferenceAddressReferenceExplicitCountryCodeBz AddressReferenceAddressReferenceExplicitCountryCode = "BZ"
	AddressReferenceAddressReferenceExplicitCountryCodeBj AddressReferenceAddressReferenceExplicitCountryCode = "BJ"
	AddressReferenceAddressReferenceExplicitCountryCodeBm AddressReferenceAddressReferenceExplicitCountryCode = "BM"
	AddressReferenceAddressReferenceExplicitCountryCodeBt AddressReferenceAddressReferenceExplicitCountryCode = "BT"
	AddressReferenceAddressReferenceExplicitCountryCodeBo AddressReferenceAddressReferenceExplicitCountryCode = "BO"
	AddressReferenceAddressReferenceExplicitCountryCodeBq AddressReferenceAddressReferenceExplicitCountryCode = "BQ"
	AddressReferenceAddressReferenceExplicitCountryCodeBa AddressReferenceAddressReferenceExplicitCountryCode = "BA"
	AddressReferenceAddressReferenceExplicitCountryCodeBw AddressReferenceAddressReferenceExplicitCountryCode = "BW"
	AddressReferenceAddressReferenceExplicitCountryCodeBv AddressReferenceAddressReferenceExplicitCountryCode = "BV"
	AddressReferenceAddressReferenceExplicitCountryCodeBr AddressReferenceAddressReferenceExplicitCountryCode = "BR"
	AddressReferenceAddressReferenceExplicitCountryCodeIo AddressReferenceAddressReferenceExplicitCountryCode = "IO"
	AddressReferenceAddressReferenceExplicitCountryCodeBn AddressReferenceAddressReferenceExplicitCountryCode = "BN"
	AddressReferenceAddressReferenceExplicitCountryCodeBg AddressReferenceAddressReferenceExplicitCountryCode = "BG"
	AddressReferenceAddressReferenceExplicitCountryCodeBf AddressReferenceAddressReferenceExplicitCountryCode = "BF"
	AddressReferenceAddressReferenceExplicitCountryCodeBi AddressReferenceAddressReferenceExplicitCountryCode = "BI"
	AddressReferenceAddressReferenceExplicitCountryCodeKh AddressReferenceAddressReferenceExplicitCountryCode = "KH"
	AddressReferenceAddressReferenceExplicitCountryCodeCm AddressReferenceAddressReferenceExplicitCountryCode = "CM"
	AddressReferenceAddressReferenceExplicitCountryCodeCa AddressReferenceAddressReferenceExplicitCountryCode = "CA"
	AddressReferenceAddressReferenceExplicitCountryCodeCv AddressReferenceAddressReferenceExplicitCountryCode = "CV"
	AddressReferenceAddressReferenceExplicitCountryCodeKy AddressReferenceAddressReferenceExplicitCountryCode = "KY"
	AddressReferenceAddressReferenceExplicitCountryCodeCf AddressReferenceAddressReferenceExplicitCountryCode = "CF"
	AddressReferenceAddressReferenceExplicitCountryCodeTd AddressReferenceAddressReferenceExplicitCountryCode = "TD"
	AddressReferenceAddressReferenceExplicitCountryCodeCl AddressReferenceAddressReferenceExplicitCountryCode = "CL"
	AddressReferenceAddressReferenceExplicitCountryCodeCn AddressReferenceAddressReferenceExplicitCountryCode = "CN"
	AddressReferenceAddressReferenceExplicitCountryCodeCx AddressReferenceAddressReferenceExplicitCountryCode = "CX"
	AddressReferenceAddressReferenceExplicitCountryCodeCc AddressReferenceAddressReferenceExplicitCountryCode = "CC"
	AddressReferenceAddressReferenceExplicitCountryCodeCo AddressReferenceAddressReferenceExplicitCountryCode = "CO"
	AddressReferenceAddressReferenceExplicitCountryCodeKm AddressReferenceAddressReferenceExplicitCountryCode = "KM"
	AddressReferenceAddressReferenceExplicitCountryCodeCg AddressReferenceAddressReferenceExplicitCountryCode = "CG"
	AddressReferenceAddressReferenceExplicitCountryCodeCd AddressReferenceAddressReferenceExplicitCountryCode = "CD"
	AddressReferenceAddressReferenceExplicitCountryCodeCk AddressReferenceAddressReferenceExplicitCountryCode = "CK"
	AddressReferenceAddressReferenceExplicitCountryCodeCr AddressReferenceAddressReferenceExplicitCountryCode = "CR"
	AddressReferenceAddressReferenceExplicitCountryCodeCi AddressReferenceAddressReferenceExplicitCountryCode = "CI"
	AddressReferenceAddressReferenceExplicitCountryCodeHr AddressReferenceAddressReferenceExplicitCountryCode = "HR"
	AddressReferenceAddressReferenceExplicitCountryCodeCu AddressReferenceAddressReferenceExplicitCountryCode = "CU"
	AddressReferenceAddressReferenceExplicitCountryCodeCw AddressReferenceAddressReferenceExplicitCountryCode = "CW"
	AddressReferenceAddressReferenceExplicitCountryCodeCy AddressReferenceAddressReferenceExplicitCountryCode = "CY"
	AddressReferenceAddressReferenceExplicitCountryCodeCz AddressReferenceAddressReferenceExplicitCountryCode = "CZ"
	AddressReferenceAddressReferenceExplicitCountryCodeDk AddressReferenceAddressReferenceExplicitCountryCode = "DK"
	AddressReferenceAddressReferenceExplicitCountryCodeDj AddressReferenceAddressReferenceExplicitCountryCode = "DJ"
	AddressReferenceAddressReferenceExplicitCountryCodeDm AddressReferenceAddressReferenceExplicitCountryCode = "DM"
	AddressReferenceAddressReferenceExplicitCountryCodeDo AddressReferenceAddressReferenceExplicitCountryCode = "DO"
	AddressReferenceAddressReferenceExplicitCountryCodeEc AddressReferenceAddressReferenceExplicitCountryCode = "EC"
	AddressReferenceAddressReferenceExplicitCountryCodeEg AddressReferenceAddressReferenceExplicitCountryCode = "EG"
	AddressReferenceAddressReferenceExplicitCountryCodeSv AddressReferenceAddressReferenceExplicitCountryCode = "SV"
	AddressReferenceAddressReferenceExplicitCountryCodeGq AddressReferenceAddressReferenceExplicitCountryCode = "GQ"
	AddressReferenceAddressReferenceExplicitCountryCodeEr AddressReferenceAddressReferenceExplicitCountryCode = "ER"
	AddressReferenceAddressReferenceExplicitCountryCodeEe AddressReferenceAddressReferenceExplicitCountryCode = "EE"
	AddressReferenceAddressReferenceExplicitCountryCodeEt AddressReferenceAddressReferenceExplicitCountryCode = "ET"
	AddressReferenceAddressReferenceExplicitCountryCodeFk AddressReferenceAddressReferenceExplicitCountryCode = "FK"
	AddressReferenceAddressReferenceExplicitCountryCodeFo AddressReferenceAddressReferenceExplicitCountryCode = "FO"
	AddressReferenceAddressReferenceExplicitCountryCodeFj AddressReferenceAddressReferenceExplicitCountryCode = "FJ"
	AddressReferenceAddressReferenceExplicitCountryCodeFi AddressReferenceAddressReferenceExplicitCountryCode = "FI"
	AddressReferenceAddressReferenceExplicitCountryCodeFr AddressReferenceAddressReferenceExplicitCountryCode = "FR"
	AddressReferenceAddressReferenceExplicitCountryCodeGf AddressReferenceAddressReferenceExplicitCountryCode = "GF"
	AddressReferenceAddressReferenceExplicitCountryCodePf AddressReferenceAddressReferenceExplicitCountryCode = "PF"
	AddressReferenceAddressReferenceExplicitCountryCodeTf AddressReferenceAddressReferenceExplicitCountryCode = "TF"
	AddressReferenceAddressReferenceExplicitCountryCodeGa AddressReferenceAddressReferenceExplicitCountryCode = "GA"
	AddressReferenceAddressReferenceExplicitCountryCodeGm AddressReferenceAddressReferenceExplicitCountryCode = "GM"
	AddressReferenceAddressReferenceExplicitCountryCodeGe AddressReferenceAddressReferenceExplicitCountryCode = "GE"
	AddressReferenceAddressReferenceExplicitCountryCodeDe AddressReferenceAddressReferenceExplicitCountryCode = "DE"
	AddressReferenceAddressReferenceExplicitCountryCodeGh AddressReferenceAddressReferenceExplicitCountryCode = "GH"
	AddressReferenceAddressReferenceExplicitCountryCodeGi AddressReferenceAddressReferenceExplicitCountryCode = "GI"
	AddressReferenceAddressReferenceExplicitCountryCodeGr AddressReferenceAddressReferenceExplicitCountryCode = "GR"
	AddressReferenceAddressReferenceExplicitCountryCodeGl AddressReferenceAddressReferenceExplicitCountryCode = "GL"
	AddressReferenceAddressReferenceExplicitCountryCodeGd AddressReferenceAddressReferenceExplicitCountryCode = "GD"
	AddressReferenceAddressReferenceExplicitCountryCodeGp AddressReferenceAddressReferenceExplicitCountryCode = "GP"
	AddressReferenceAddressReferenceExplicitCountryCodeGu AddressReferenceAddressReferenceExplicitCountryCode = "GU"
	AddressReferenceAddressReferenceExplicitCountryCodeGt AddressReferenceAddressReferenceExplicitCountryCode = "GT"
	AddressReferenceAddressReferenceExplicitCountryCodeGg AddressReferenceAddressReferenceExplicitCountryCode = "GG"
	AddressReferenceAddressReferenceExplicitCountryCodeGn AddressReferenceAddressReferenceExplicitCountryCode = "GN"
	AddressReferenceAddressReferenceExplicitCountryCodeGw AddressReferenceAddressReferenceExplicitCountryCode = "GW"
	AddressReferenceAddressReferenceExplicitCountryCodeGy AddressReferenceAddressReferenceExplicitCountryCode = "GY"
	AddressReferenceAddressReferenceExplicitCountryCodeHt AddressReferenceAddressReferenceExplicitCountryCode = "HT"
	AddressReferenceAddressReferenceExplicitCountryCodeHm AddressReferenceAddressReferenceExplicitCountryCode = "HM"
	AddressReferenceAddressReferenceExplicitCountryCodeVa AddressReferenceAddressReferenceExplicitCountryCode = "VA"
	AddressReferenceAddressReferenceExplicitCountryCodeHn AddressReferenceAddressReferenceExplicitCountryCode = "HN"
	AddressReferenceAddressReferenceExplicitCountryCodeHk AddressReferenceAddressReferenceExplicitCountryCode = "HK"
	AddressReferenceAddressReferenceExplicitCountryCodeHu AddressReferenceAddressReferenceExplicitCountryCode = "HU"
	AddressReferenceAddressReferenceExplicitCountryCodeIs AddressReferenceAddressReferenceExplicitCountryCode = "IS"
	AddressReferenceAddressReferenceExplicitCountryCodeIn AddressReferenceAddressReferenceExplicitCountryCode = "IN"
	AddressReferenceAddressReferenceExplicitCountryCodeID AddressReferenceAddressReferenceExplicitCountryCode = "ID"
	AddressReferenceAddressReferenceExplicitCountryCodeIr AddressReferenceAddressReferenceExplicitCountryCode = "IR"
	AddressReferenceAddressReferenceExplicitCountryCodeIq AddressReferenceAddressReferenceExplicitCountryCode = "IQ"
	AddressReferenceAddressReferenceExplicitCountryCodeIe AddressReferenceAddressReferenceExplicitCountryCode = "IE"
	AddressReferenceAddressReferenceExplicitCountryCodeIm AddressReferenceAddressReferenceExplicitCountryCode = "IM"
	AddressReferenceAddressReferenceExplicitCountryCodeIl AddressReferenceAddressReferenceExplicitCountryCode = "IL"
	AddressReferenceAddressReferenceExplicitCountryCodeIt AddressReferenceAddressReferenceExplicitCountryCode = "IT"
	AddressReferenceAddressReferenceExplicitCountryCodeJm AddressReferenceAddressReferenceExplicitCountryCode = "JM"
	AddressReferenceAddressReferenceExplicitCountryCodeJp AddressReferenceAddressReferenceExplicitCountryCode = "JP"
	AddressReferenceAddressReferenceExplicitCountryCodeJe AddressReferenceAddressReferenceExplicitCountryCode = "JE"
	AddressReferenceAddressReferenceExplicitCountryCodeJo AddressReferenceAddressReferenceExplicitCountryCode = "JO"
	AddressReferenceAddressReferenceExplicitCountryCodeKz AddressReferenceAddressReferenceExplicitCountryCode = "KZ"
	AddressReferenceAddressReferenceExplicitCountryCodeKe AddressReferenceAddressReferenceExplicitCountryCode = "KE"
	AddressReferenceAddressReferenceExplicitCountryCodeKi AddressReferenceAddressReferenceExplicitCountryCode = "KI"
	AddressReferenceAddressReferenceExplicitCountryCodeKp AddressReferenceAddressReferenceExplicitCountryCode = "KP"
	AddressReferenceAddressReferenceExplicitCountryCodeKr AddressReferenceAddressReferenceExplicitCountryCode = "KR"
	AddressReferenceAddressReferenceExplicitCountryCodeKw AddressReferenceAddressReferenceExplicitCountryCode = "KW"
	AddressReferenceAddressReferenceExplicitCountryCodeKg AddressReferenceAddressReferenceExplicitCountryCode = "KG"
	AddressReferenceAddressReferenceExplicitCountryCodeLa AddressReferenceAddressReferenceExplicitCountryCode = "LA"
	AddressReferenceAddressReferenceExplicitCountryCodeLv AddressReferenceAddressReferenceExplicitCountryCode = "LV"
	AddressReferenceAddressReferenceExplicitCountryCodeLb AddressReferenceAddressReferenceExplicitCountryCode = "LB"
	AddressReferenceAddressReferenceExplicitCountryCodeLs AddressReferenceAddressReferenceExplicitCountryCode = "LS"
	AddressReferenceAddressReferenceExplicitCountryCodeLr AddressReferenceAddressReferenceExplicitCountryCode = "LR"
	AddressReferenceAddressReferenceExplicitCountryCodeLy AddressReferenceAddressReferenceExplicitCountryCode = "LY"
	AddressReferenceAddressReferenceExplicitCountryCodeLi AddressReferenceAddressReferenceExplicitCountryCode = "LI"
	AddressReferenceAddressReferenceExplicitCountryCodeLt AddressReferenceAddressReferenceExplicitCountryCode = "LT"
	AddressReferenceAddressReferenceExplicitCountryCodeLu AddressReferenceAddressReferenceExplicitCountryCode = "LU"
	AddressReferenceAddressReferenceExplicitCountryCodeMo AddressReferenceAddressReferenceExplicitCountryCode = "MO"
	AddressReferenceAddressReferenceExplicitCountryCodeMk AddressReferenceAddressReferenceExplicitCountryCode = "MK"
	AddressReferenceAddressReferenceExplicitCountryCodeMg AddressReferenceAddressReferenceExplicitCountryCode = "MG"
	AddressReferenceAddressReferenceExplicitCountryCodeMw AddressReferenceAddressReferenceExplicitCountryCode = "MW"
	AddressReferenceAddressReferenceExplicitCountryCodeMy AddressReferenceAddressReferenceExplicitCountryCode = "MY"
	AddressReferenceAddressReferenceExplicitCountryCodeMv AddressReferenceAddressReferenceExplicitCountryCode = "MV"
	AddressReferenceAddressReferenceExplicitCountryCodeMl AddressReferenceAddressReferenceExplicitCountryCode = "ML"
	AddressReferenceAddressReferenceExplicitCountryCodeMt AddressReferenceAddressReferenceExplicitCountryCode = "MT"
	AddressReferenceAddressReferenceExplicitCountryCodeMh AddressReferenceAddressReferenceExplicitCountryCode = "MH"
	AddressReferenceAddressReferenceExplicitCountryCodeMq AddressReferenceAddressReferenceExplicitCountryCode = "MQ"
	AddressReferenceAddressReferenceExplicitCountryCodeMr AddressReferenceAddressReferenceExplicitCountryCode = "MR"
	AddressReferenceAddressReferenceExplicitCountryCodeMu AddressReferenceAddressReferenceExplicitCountryCode = "MU"
	AddressReferenceAddressReferenceExplicitCountryCodeYt AddressReferenceAddressReferenceExplicitCountryCode = "YT"
	AddressReferenceAddressReferenceExplicitCountryCodeMx AddressReferenceAddressReferenceExplicitCountryCode = "MX"
	AddressReferenceAddressReferenceExplicitCountryCodeFm AddressReferenceAddressReferenceExplicitCountryCode = "FM"
	AddressReferenceAddressReferenceExplicitCountryCodeMd AddressReferenceAddressReferenceExplicitCountryCode = "MD"
	AddressReferenceAddressReferenceExplicitCountryCodeMc AddressReferenceAddressReferenceExplicitCountryCode = "MC"
	AddressReferenceAddressReferenceExplicitCountryCodeMn AddressReferenceAddressReferenceExplicitCountryCode = "MN"
	AddressReferenceAddressReferenceExplicitCountryCodeMe AddressReferenceAddressReferenceExplicitCountryCode = "ME"
	AddressReferenceAddressReferenceExplicitCountryCodeMs AddressReferenceAddressReferenceExplicitCountryCode = "MS"
	AddressReferenceAddressReferenceExplicitCountryCodeMa AddressReferenceAddressReferenceExplicitCountryCode = "MA"
	AddressReferenceAddressReferenceExplicitCountryCodeMz AddressReferenceAddressReferenceExplicitCountryCode = "MZ"
	AddressReferenceAddressReferenceExplicitCountryCodeMm AddressReferenceAddressReferenceExplicitCountryCode = "MM"
	AddressReferenceAddressReferenceExplicitCountryCodeNa AddressReferenceAddressReferenceExplicitCountryCode = "NA"
	AddressReferenceAddressReferenceExplicitCountryCodeNr AddressReferenceAddressReferenceExplicitCountryCode = "NR"
	AddressReferenceAddressReferenceExplicitCountryCodeNp AddressReferenceAddressReferenceExplicitCountryCode = "NP"
	AddressReferenceAddressReferenceExplicitCountryCodeNl AddressReferenceAddressReferenceExplicitCountryCode = "NL"
	AddressReferenceAddressReferenceExplicitCountryCodeNc AddressReferenceAddressReferenceExplicitCountryCode = "NC"
	AddressReferenceAddressReferenceExplicitCountryCodeNz AddressReferenceAddressReferenceExplicitCountryCode = "NZ"
	AddressReferenceAddressReferenceExplicitCountryCodeNi AddressReferenceAddressReferenceExplicitCountryCode = "NI"
	AddressReferenceAddressReferenceExplicitCountryCodeNe AddressReferenceAddressReferenceExplicitCountryCode = "NE"
	AddressReferenceAddressReferenceExplicitCountryCodeNg AddressReferenceAddressReferenceExplicitCountryCode = "NG"
	AddressReferenceAddressReferenceExplicitCountryCodeNu AddressReferenceAddressReferenceExplicitCountryCode = "NU"
	AddressReferenceAddressReferenceExplicitCountryCodeNf AddressReferenceAddressReferenceExplicitCountryCode = "NF"
	AddressReferenceAddressReferenceExplicitCountryCodeMp AddressReferenceAddressReferenceExplicitCountryCode = "MP"
	AddressReferenceAddressReferenceExplicitCountryCodeNo AddressReferenceAddressReferenceExplicitCountryCode = "NO"
	AddressReferenceAddressReferenceExplicitCountryCodeOm AddressReferenceAddressReferenceExplicitCountryCode = "OM"
	AddressReferenceAddressReferenceExplicitCountryCodePk AddressReferenceAddressReferenceExplicitCountryCode = "PK"
	AddressReferenceAddressReferenceExplicitCountryCodePw AddressReferenceAddressReferenceExplicitCountryCode = "PW"
	AddressReferenceAddressReferenceExplicitCountryCodePs AddressReferenceAddressReferenceExplicitCountryCode = "PS"
	AddressReferenceAddressReferenceExplicitCountryCodePa AddressReferenceAddressReferenceExplicitCountryCode = "PA"
	AddressReferenceAddressReferenceExplicitCountryCodePg AddressReferenceAddressReferenceExplicitCountryCode = "PG"
	AddressReferenceAddressReferenceExplicitCountryCodePy AddressReferenceAddressReferenceExplicitCountryCode = "PY"
	AddressReferenceAddressReferenceExplicitCountryCodePe AddressReferenceAddressReferenceExplicitCountryCode = "PE"
	AddressReferenceAddressReferenceExplicitCountryCodePh AddressReferenceAddressReferenceExplicitCountryCode = "PH"
	AddressReferenceAddressReferenceExplicitCountryCodePn AddressReferenceAddressReferenceExplicitCountryCode = "PN"
	AddressReferenceAddressReferenceExplicitCountryCodePl AddressReferenceAddressReferenceExplicitCountryCode = "PL"
	AddressReferenceAddressReferenceExplicitCountryCodePt AddressReferenceAddressReferenceExplicitCountryCode = "PT"
	AddressReferenceAddressReferenceExplicitCountryCodePr AddressReferenceAddressReferenceExplicitCountryCode = "PR"
	AddressReferenceAddressReferenceExplicitCountryCodeQa AddressReferenceAddressReferenceExplicitCountryCode = "QA"
	AddressReferenceAddressReferenceExplicitCountryCodeRe AddressReferenceAddressReferenceExplicitCountryCode = "RE"
	AddressReferenceAddressReferenceExplicitCountryCodeRo AddressReferenceAddressReferenceExplicitCountryCode = "RO"
	AddressReferenceAddressReferenceExplicitCountryCodeRu AddressReferenceAddressReferenceExplicitCountryCode = "RU"
	AddressReferenceAddressReferenceExplicitCountryCodeRw AddressReferenceAddressReferenceExplicitCountryCode = "RW"
	AddressReferenceAddressReferenceExplicitCountryCodeBl AddressReferenceAddressReferenceExplicitCountryCode = "BL"
	AddressReferenceAddressReferenceExplicitCountryCodeSh AddressReferenceAddressReferenceExplicitCountryCode = "SH"
	AddressReferenceAddressReferenceExplicitCountryCodeKn AddressReferenceAddressReferenceExplicitCountryCode = "KN"
	AddressReferenceAddressReferenceExplicitCountryCodeLc AddressReferenceAddressReferenceExplicitCountryCode = "LC"
	AddressReferenceAddressReferenceExplicitCountryCodeMf AddressReferenceAddressReferenceExplicitCountryCode = "MF"
	AddressReferenceAddressReferenceExplicitCountryCodePm AddressReferenceAddressReferenceExplicitCountryCode = "PM"
	AddressReferenceAddressReferenceExplicitCountryCodeVc AddressReferenceAddressReferenceExplicitCountryCode = "VC"
	AddressReferenceAddressReferenceExplicitCountryCodeWs AddressReferenceAddressReferenceExplicitCountryCode = "WS"
	AddressReferenceAddressReferenceExplicitCountryCodeSm AddressReferenceAddressReferenceExplicitCountryCode = "SM"
	AddressReferenceAddressReferenceExplicitCountryCodeSt AddressReferenceAddressReferenceExplicitCountryCode = "ST"
	AddressReferenceAddressReferenceExplicitCountryCodeSa AddressReferenceAddressReferenceExplicitCountryCode = "SA"
	AddressReferenceAddressReferenceExplicitCountryCodeSn AddressReferenceAddressReferenceExplicitCountryCode = "SN"
	AddressReferenceAddressReferenceExplicitCountryCodeRs AddressReferenceAddressReferenceExplicitCountryCode = "RS"
	AddressReferenceAddressReferenceExplicitCountryCodeSc AddressReferenceAddressReferenceExplicitCountryCode = "SC"
	AddressReferenceAddressReferenceExplicitCountryCodeSl AddressReferenceAddressReferenceExplicitCountryCode = "SL"
	AddressReferenceAddressReferenceExplicitCountryCodeSg AddressReferenceAddressReferenceExplicitCountryCode = "SG"
	AddressReferenceAddressReferenceExplicitCountryCodeSx AddressReferenceAddressReferenceExplicitCountryCode = "SX"
	AddressReferenceAddressReferenceExplicitCountryCodeSk AddressReferenceAddressReferenceExplicitCountryCode = "SK"
	AddressReferenceAddressReferenceExplicitCountryCodeSi AddressReferenceAddressReferenceExplicitCountryCode = "SI"
	AddressReferenceAddressReferenceExplicitCountryCodeSb AddressReferenceAddressReferenceExplicitCountryCode = "SB"
	AddressReferenceAddressReferenceExplicitCountryCodeSo AddressReferenceAddressReferenceExplicitCountryCode = "SO"
	AddressReferenceAddressReferenceExplicitCountryCodeZa AddressReferenceAddressReferenceExplicitCountryCode = "ZA"
	AddressReferenceAddressReferenceExplicitCountryCodeGs AddressReferenceAddressReferenceExplicitCountryCode = "GS"
	AddressReferenceAddressReferenceExplicitCountryCodeSs AddressReferenceAddressReferenceExplicitCountryCode = "SS"
	AddressReferenceAddressReferenceExplicitCountryCodeEs AddressReferenceAddressReferenceExplicitCountryCode = "ES"
	AddressReferenceAddressReferenceExplicitCountryCodeLk AddressReferenceAddressReferenceExplicitCountryCode = "LK"
	AddressReferenceAddressReferenceExplicitCountryCodeSd AddressReferenceAddressReferenceExplicitCountryCode = "SD"
	AddressReferenceAddressReferenceExplicitCountryCodeSr AddressReferenceAddressReferenceExplicitCountryCode = "SR"
	AddressReferenceAddressReferenceExplicitCountryCodeSj AddressReferenceAddressReferenceExplicitCountryCode = "SJ"
	AddressReferenceAddressReferenceExplicitCountryCodeSz AddressReferenceAddressReferenceExplicitCountryCode = "SZ"
	AddressReferenceAddressReferenceExplicitCountryCodeSe AddressReferenceAddressReferenceExplicitCountryCode = "SE"
	AddressReferenceAddressReferenceExplicitCountryCodeCh AddressReferenceAddressReferenceExplicitCountryCode = "CH"
	AddressReferenceAddressReferenceExplicitCountryCodeSy AddressReferenceAddressReferenceExplicitCountryCode = "SY"
	AddressReferenceAddressReferenceExplicitCountryCodeTw AddressReferenceAddressReferenceExplicitCountryCode = "TW"
	AddressReferenceAddressReferenceExplicitCountryCodeTj AddressReferenceAddressReferenceExplicitCountryCode = "TJ"
	AddressReferenceAddressReferenceExplicitCountryCodeTz AddressReferenceAddressReferenceExplicitCountryCode = "TZ"
	AddressReferenceAddressReferenceExplicitCountryCodeTh AddressReferenceAddressReferenceExplicitCountryCode = "TH"
	AddressReferenceAddressReferenceExplicitCountryCodeTl AddressReferenceAddressReferenceExplicitCountryCode = "TL"
	AddressReferenceAddressReferenceExplicitCountryCodeTg AddressReferenceAddressReferenceExplicitCountryCode = "TG"
	AddressReferenceAddressReferenceExplicitCountryCodeTk AddressReferenceAddressReferenceExplicitCountryCode = "TK"
	AddressReferenceAddressReferenceExplicitCountryCodeTo AddressReferenceAddressReferenceExplicitCountryCode = "TO"
	AddressReferenceAddressReferenceExplicitCountryCodeTt AddressReferenceAddressReferenceExplicitCountryCode = "TT"
	AddressReferenceAddressReferenceExplicitCountryCodeTn AddressReferenceAddressReferenceExplicitCountryCode = "TN"
	AddressReferenceAddressReferenceExplicitCountryCodeTr AddressReferenceAddressReferenceExplicitCountryCode = "TR"
	AddressReferenceAddressReferenceExplicitCountryCodeTm AddressReferenceAddressReferenceExplicitCountryCode = "TM"
	AddressReferenceAddressReferenceExplicitCountryCodeTc AddressReferenceAddressReferenceExplicitCountryCode = "TC"
	AddressReferenceAddressReferenceExplicitCountryCodeTv AddressReferenceAddressReferenceExplicitCountryCode = "TV"
	AddressReferenceAddressReferenceExplicitCountryCodeUg AddressReferenceAddressReferenceExplicitCountryCode = "UG"
	AddressReferenceAddressReferenceExplicitCountryCodeUa AddressReferenceAddressReferenceExplicitCountryCode = "UA"
	AddressReferenceAddressReferenceExplicitCountryCodeAe AddressReferenceAddressReferenceExplicitCountryCode = "AE"
	AddressReferenceAddressReferenceExplicitCountryCodeGb AddressReferenceAddressReferenceExplicitCountryCode = "GB"
	AddressReferenceAddressReferenceExplicitCountryCodeUs AddressReferenceAddressReferenceExplicitCountryCode = "US"
	AddressReferenceAddressReferenceExplicitCountryCodeUm AddressReferenceAddressReferenceExplicitCountryCode = "UM"
	AddressReferenceAddressReferenceExplicitCountryCodeUy AddressReferenceAddressReferenceExplicitCountryCode = "UY"
	AddressReferenceAddressReferenceExplicitCountryCodeUz AddressReferenceAddressReferenceExplicitCountryCode = "UZ"
	AddressReferenceAddressReferenceExplicitCountryCodeVu AddressReferenceAddressReferenceExplicitCountryCode = "VU"
	AddressReferenceAddressReferenceExplicitCountryCodeVe AddressReferenceAddressReferenceExplicitCountryCode = "VE"
	AddressReferenceAddressReferenceExplicitCountryCodeVn AddressReferenceAddressReferenceExplicitCountryCode = "VN"
	AddressReferenceAddressReferenceExplicitCountryCodeVg AddressReferenceAddressReferenceExplicitCountryCode = "VG"
	AddressReferenceAddressReferenceExplicitCountryCodeVi AddressReferenceAddressReferenceExplicitCountryCode = "VI"
	AddressReferenceAddressReferenceExplicitCountryCodeWf AddressReferenceAddressReferenceExplicitCountryCode = "WF"
	AddressReferenceAddressReferenceExplicitCountryCodeEh AddressReferenceAddressReferenceExplicitCountryCode = "EH"
	AddressReferenceAddressReferenceExplicitCountryCodeYe AddressReferenceAddressReferenceExplicitCountryCode = "YE"
	AddressReferenceAddressReferenceExplicitCountryCodeZm AddressReferenceAddressReferenceExplicitCountryCode = "ZM"
	AddressReferenceAddressReferenceExplicitCountryCodeZw AddressReferenceAddressReferenceExplicitCountryCode = "ZW"
)

func (e AddressReferenceAddressReferenceExplicitCountryCode) ToPointer() *AddressReferenceAddressReferenceExplicitCountryCode {
	return &e
}

func (e *AddressReferenceAddressReferenceExplicitCountryCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AF":
		fallthrough
	case "AX":
		fallthrough
	case "AL":
		fallthrough
	case "DZ":
		fallthrough
	case "AS":
		fallthrough
	case "AD":
		fallthrough
	case "AO":
		fallthrough
	case "AI":
		fallthrough
	case "AQ":
		fallthrough
	case "AG":
		fallthrough
	case "AR":
		fallthrough
	case "AM":
		fallthrough
	case "AW":
		fallthrough
	case "AU":
		fallthrough
	case "AT":
		fallthrough
	case "AZ":
		fallthrough
	case "BH":
		fallthrough
	case "BS":
		fallthrough
	case "BD":
		fallthrough
	case "BB":
		fallthrough
	case "BY":
		fallthrough
	case "BE":
		fallthrough
	case "BZ":
		fallthrough
	case "BJ":
		fallthrough
	case "BM":
		fallthrough
	case "BT":
		fallthrough
	case "BO":
		fallthrough
	case "BQ":
		fallthrough
	case "BA":
		fallthrough
	case "BW":
		fallthrough
	case "BV":
		fallthrough
	case "BR":
		fallthrough
	case "IO":
		fallthrough
	case "BN":
		fallthrough
	case "BG":
		fallthrough
	case "BF":
		fallthrough
	case "BI":
		fallthrough
	case "KH":
		fallthrough
	case "CM":
		fallthrough
	case "CA":
		fallthrough
	case "CV":
		fallthrough
	case "KY":
		fallthrough
	case "CF":
		fallthrough
	case "TD":
		fallthrough
	case "CL":
		fallthrough
	case "CN":
		fallthrough
	case "CX":
		fallthrough
	case "CC":
		fallthrough
	case "CO":
		fallthrough
	case "KM":
		fallthrough
	case "CG":
		fallthrough
	case "CD":
		fallthrough
	case "CK":
		fallthrough
	case "CR":
		fallthrough
	case "CI":
		fallthrough
	case "HR":
		fallthrough
	case "CU":
		fallthrough
	case "CW":
		fallthrough
	case "CY":
		fallthrough
	case "CZ":
		fallthrough
	case "DK":
		fallthrough
	case "DJ":
		fallthrough
	case "DM":
		fallthrough
	case "DO":
		fallthrough
	case "EC":
		fallthrough
	case "EG":
		fallthrough
	case "SV":
		fallthrough
	case "GQ":
		fallthrough
	case "ER":
		fallthrough
	case "EE":
		fallthrough
	case "ET":
		fallthrough
	case "FK":
		fallthrough
	case "FO":
		fallthrough
	case "FJ":
		fallthrough
	case "FI":
		fallthrough
	case "FR":
		fallthrough
	case "GF":
		fallthrough
	case "PF":
		fallthrough
	case "TF":
		fallthrough
	case "GA":
		fallthrough
	case "GM":
		fallthrough
	case "GE":
		fallthrough
	case "DE":
		fallthrough
	case "GH":
		fallthrough
	case "GI":
		fallthrough
	case "GR":
		fallthrough
	case "GL":
		fallthrough
	case "GD":
		fallthrough
	case "GP":
		fallthrough
	case "GU":
		fallthrough
	case "GT":
		fallthrough
	case "GG":
		fallthrough
	case "GN":
		fallthrough
	case "GW":
		fallthrough
	case "GY":
		fallthrough
	case "HT":
		fallthrough
	case "HM":
		fallthrough
	case "VA":
		fallthrough
	case "HN":
		fallthrough
	case "HK":
		fallthrough
	case "HU":
		fallthrough
	case "IS":
		fallthrough
	case "IN":
		fallthrough
	case "ID":
		fallthrough
	case "IR":
		fallthrough
	case "IQ":
		fallthrough
	case "IE":
		fallthrough
	case "IM":
		fallthrough
	case "IL":
		fallthrough
	case "IT":
		fallthrough
	case "JM":
		fallthrough
	case "JP":
		fallthrough
	case "JE":
		fallthrough
	case "JO":
		fallthrough
	case "KZ":
		fallthrough
	case "KE":
		fallthrough
	case "KI":
		fallthrough
	case "KP":
		fallthrough
	case "KR":
		fallthrough
	case "KW":
		fallthrough
	case "KG":
		fallthrough
	case "LA":
		fallthrough
	case "LV":
		fallthrough
	case "LB":
		fallthrough
	case "LS":
		fallthrough
	case "LR":
		fallthrough
	case "LY":
		fallthrough
	case "LI":
		fallthrough
	case "LT":
		fallthrough
	case "LU":
		fallthrough
	case "MO":
		fallthrough
	case "MK":
		fallthrough
	case "MG":
		fallthrough
	case "MW":
		fallthrough
	case "MY":
		fallthrough
	case "MV":
		fallthrough
	case "ML":
		fallthrough
	case "MT":
		fallthrough
	case "MH":
		fallthrough
	case "MQ":
		fallthrough
	case "MR":
		fallthrough
	case "MU":
		fallthrough
	case "YT":
		fallthrough
	case "MX":
		fallthrough
	case "FM":
		fallthrough
	case "MD":
		fallthrough
	case "MC":
		fallthrough
	case "MN":
		fallthrough
	case "ME":
		fallthrough
	case "MS":
		fallthrough
	case "MA":
		fallthrough
	case "MZ":
		fallthrough
	case "MM":
		fallthrough
	case "NA":
		fallthrough
	case "NR":
		fallthrough
	case "NP":
		fallthrough
	case "NL":
		fallthrough
	case "NC":
		fallthrough
	case "NZ":
		fallthrough
	case "NI":
		fallthrough
	case "NE":
		fallthrough
	case "NG":
		fallthrough
	case "NU":
		fallthrough
	case "NF":
		fallthrough
	case "MP":
		fallthrough
	case "NO":
		fallthrough
	case "OM":
		fallthrough
	case "PK":
		fallthrough
	case "PW":
		fallthrough
	case "PS":
		fallthrough
	case "PA":
		fallthrough
	case "PG":
		fallthrough
	case "PY":
		fallthrough
	case "PE":
		fallthrough
	case "PH":
		fallthrough
	case "PN":
		fallthrough
	case "PL":
		fallthrough
	case "PT":
		fallthrough
	case "PR":
		fallthrough
	case "QA":
		fallthrough
	case "RE":
		fallthrough
	case "RO":
		fallthrough
	case "RU":
		fallthrough
	case "RW":
		fallthrough
	case "BL":
		fallthrough
	case "SH":
		fallthrough
	case "KN":
		fallthrough
	case "LC":
		fallthrough
	case "MF":
		fallthrough
	case "PM":
		fallthrough
	case "VC":
		fallthrough
	case "WS":
		fallthrough
	case "SM":
		fallthrough
	case "ST":
		fallthrough
	case "SA":
		fallthrough
	case "SN":
		fallthrough
	case "RS":
		fallthrough
	case "SC":
		fallthrough
	case "SL":
		fallthrough
	case "SG":
		fallthrough
	case "SX":
		fallthrough
	case "SK":
		fallthrough
	case "SI":
		fallthrough
	case "SB":
		fallthrough
	case "SO":
		fallthrough
	case "ZA":
		fallthrough
	case "GS":
		fallthrough
	case "SS":
		fallthrough
	case "ES":
		fallthrough
	case "LK":
		fallthrough
	case "SD":
		fallthrough
	case "SR":
		fallthrough
	case "SJ":
		fallthrough
	case "SZ":
		fallthrough
	case "SE":
		fallthrough
	case "CH":
		fallthrough
	case "SY":
		fallthrough
	case "TW":
		fallthrough
	case "TJ":
		fallthrough
	case "TZ":
		fallthrough
	case "TH":
		fallthrough
	case "TL":
		fallthrough
	case "TG":
		fallthrough
	case "TK":
		fallthrough
	case "TO":
		fallthrough
	case "TT":
		fallthrough
	case "TN":
		fallthrough
	case "TR":
		fallthrough
	case "TM":
		fallthrough
	case "TC":
		fallthrough
	case "TV":
		fallthrough
	case "UG":
		fallthrough
	case "UA":
		fallthrough
	case "AE":
		fallthrough
	case "GB":
		fallthrough
	case "US":
		fallthrough
	case "UM":
		fallthrough
	case "UY":
		fallthrough
	case "UZ":
		fallthrough
	case "VU":
		fallthrough
	case "VE":
		fallthrough
	case "VN":
		fallthrough
	case "VG":
		fallthrough
	case "VI":
		fallthrough
	case "WF":
		fallthrough
	case "EH":
		fallthrough
	case "YE":
		fallthrough
	case "ZM":
		fallthrough
	case "ZW":
		*e = AddressReferenceAddressReferenceExplicitCountryCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AddressReferenceAddressReferenceExplicitCountryCode: %v", v)
	}
}

// AddressReferenceAddressReferenceExplicitInput - A physical address.
type AddressReferenceAddressReferenceExplicitInput struct {
	// The type of address reference
	DotTag AddressReferenceAddressReferenceExplicitTag `json:".tag"`
	// The company associated with this address.
	Company *string `json:"company,omitempty"`
	// The country (in its ISO 3166 alpha-2 format) associated with this address.
	CountryCode AddressReferenceAddressReferenceExplicitCountryCode `json:"country_code"`
	// The email address associated with this address.
	Email *string `json:"email,omitempty"`
	// The first name of the person associated with this address.
	FirstName string `json:"first_name"`
	// The last name of the person associated with this address.
	LastName string `json:"last_name"`
	// The locality (e.g. city, town, etc...) associated with this address.
	Locality string `json:"locality"`
	// The phone number associated with this address.
	Phone *string `json:"phone,omitempty"`
	// The postal code associated with this address.
	PostalCode string `json:"postal_code"`
	// The region or administrative area (e.g. state, province, county, etc...) associated with this address.
	Region *string `json:"region,omitempty"`
	// The street address associated with this address.
	StreetAddress1 string `json:"street_address1"`
	// Any additional, optional, street address information associated with this address.
	StreetAddress2 *string `json:"street_address2,omitempty"`
}

func (o *AddressReferenceAddressReferenceExplicitInput) GetDotTag() AddressReferenceAddressReferenceExplicitTag {
	if o == nil {
		return AddressReferenceAddressReferenceExplicitTag("")
	}
	return o.DotTag
}

func (o *AddressReferenceAddressReferenceExplicitInput) GetCompany() *string {
	if o == nil {
		return nil
	}
	return o.Company
}

func (o *AddressReferenceAddressReferenceExplicitInput) GetCountryCode() AddressReferenceAddressReferenceExplicitCountryCode {
	if o == nil {
		return AddressReferenceAddressReferenceExplicitCountryCode("")
	}
	return o.CountryCode
}

func (o *AddressReferenceAddressReferenceExplicitInput) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *AddressReferenceAddressReferenceExplicitInput) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *AddressReferenceAddressReferenceExplicitInput) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *AddressReferenceAddressReferenceExplicitInput) GetLocality() string {
	if o == nil {
		return ""
	}
	return o.Locality
}

func (o *AddressReferenceAddressReferenceExplicitInput) GetPhone() *string {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *AddressReferenceAddressReferenceExplicitInput) GetPostalCode() string {
	if o == nil {
		return ""
	}
	return o.PostalCode
}

func (o *AddressReferenceAddressReferenceExplicitInput) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *AddressReferenceAddressReferenceExplicitInput) GetStreetAddress1() string {
	if o == nil {
		return ""
	}
	return o.StreetAddress1
}

func (o *AddressReferenceAddressReferenceExplicitInput) GetStreetAddress2() *string {
	if o == nil {
		return nil
	}
	return o.StreetAddress2
}

// AddressReferenceAddressReferenceIDTag - The type of address reference
type AddressReferenceAddressReferenceIDTag string

const (
	AddressReferenceAddressReferenceIDTagID AddressReferenceAddressReferenceIDTag = "id"
)

func (e AddressReferenceAddressReferenceIDTag) ToPointer() *AddressReferenceAddressReferenceIDTag {
	return &e
}

func (e *AddressReferenceAddressReferenceIDTag) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		*e = AddressReferenceAddressReferenceIDTag(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AddressReferenceAddressReferenceIDTag: %v", v)
	}
}

type AddressReferenceAddressReferenceID struct {
	// The type of address reference
	DotTag AddressReferenceAddressReferenceIDTag `json:".tag"`
	// The address's ID
	ID string `json:"id"`
}

func (o *AddressReferenceAddressReferenceID) GetDotTag() AddressReferenceAddressReferenceIDTag {
	if o == nil {
		return AddressReferenceAddressReferenceIDTag("")
	}
	return o.DotTag
}

func (o *AddressReferenceAddressReferenceID) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type AddressReferenceInputType string

const (
	AddressReferenceInputTypeExplicit AddressReferenceInputType = "explicit"
	AddressReferenceInputTypeID       AddressReferenceInputType = "id"
)

type AddressReferenceInput struct {
	AddressReferenceAddressReferenceID            *AddressReferenceAddressReferenceID
	AddressReferenceAddressReferenceExplicitInput *AddressReferenceAddressReferenceExplicitInput

	Type AddressReferenceInputType
}

func CreateAddressReferenceInputExplicit(explicit AddressReferenceAddressReferenceExplicitInput) AddressReferenceInput {
	typ := AddressReferenceInputTypeExplicit
	typStr := AddressReferenceAddressReferenceExplicitTag(typ)
	explicit.DotTag = typStr

	return AddressReferenceInput{
		AddressReferenceAddressReferenceExplicitInput: &explicit,
		Type: typ,
	}
}

func CreateAddressReferenceInputID(id AddressReferenceAddressReferenceID) AddressReferenceInput {
	typ := AddressReferenceInputTypeID
	typStr := AddressReferenceAddressReferenceIDTag(typ)
	id.DotTag = typStr

	return AddressReferenceInput{
		AddressReferenceAddressReferenceID: &id,
		Type:                               typ,
	}
}

func (u *AddressReferenceInput) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		DotTag string
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.DotTag {
	case "explicit":
		addressReferenceAddressReferenceExplicitInput := new(AddressReferenceAddressReferenceExplicitInput)
		if err := utils.UnmarshalJSON(data, &addressReferenceAddressReferenceExplicitInput, "", true, true); err != nil {
			return fmt.Errorf("could not unmarshal expected type: %w", err)
		}

		u.AddressReferenceAddressReferenceExplicitInput = addressReferenceAddressReferenceExplicitInput
		u.Type = AddressReferenceInputTypeExplicit
		return nil
	case "id":
		addressReferenceAddressReferenceID := new(AddressReferenceAddressReferenceID)
		if err := utils.UnmarshalJSON(data, &addressReferenceAddressReferenceID, "", true, true); err != nil {
			return fmt.Errorf("could not unmarshal expected type: %w", err)
		}

		u.AddressReferenceAddressReferenceID = addressReferenceAddressReferenceID
		u.Type = AddressReferenceInputTypeID
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u AddressReferenceInput) MarshalJSON() ([]byte, error) {
	if u.AddressReferenceAddressReferenceID != nil {
		return utils.MarshalJSON(u.AddressReferenceAddressReferenceID, "", true)
	}

	if u.AddressReferenceAddressReferenceExplicitInput != nil {
		return utils.MarshalJSON(u.AddressReferenceAddressReferenceExplicitInput, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}
