// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// AmountCurrency - A supported currency.
type AmountCurrency string

const (
	AmountCurrencyAud AmountCurrency = "AUD"
	AmountCurrencyCad AmountCurrency = "CAD"
	AmountCurrencyEur AmountCurrency = "EUR"
	AmountCurrencyGbp AmountCurrency = "GBP"
	AmountCurrencyUsd AmountCurrency = "USD"
)

func (e AmountCurrency) ToPointer() *AmountCurrency {
	return &e
}

func (e *AmountCurrency) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AUD":
		fallthrough
	case "CAD":
		fallthrough
	case "EUR":
		fallthrough
	case "GBP":
		fallthrough
	case "USD":
		*e = AmountCurrency(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AmountCurrency: %v", v)
	}
}

// Amount - A monetary amount, i.e. a base unit amount and a supported currency.
type Amount struct {
	// A supported currency.
	Currency AmountCurrency `json:"currency"`
	// A monetary amount, represented in its base units (e.g. USD/EUR cents).
	Units int64 `json:"units"`
}

func (o *Amount) GetCurrency() AmountCurrency {
	if o == nil {
		return AmountCurrency("")
	}
	return o.Currency
}

func (o *Amount) GetUnits() int64 {
	if o == nil {
		return 0
	}
	return o.Units
}
