// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CartShipment struct {
	Address *AddressReferenceInput `json:"address,omitempty"`
	// The name of the carrier selected.
	Carrier *string `json:"carrier,omitempty"`
	// A monetary amount, i.e. a base unit amount and a supported currency.
	Cost *Amount `json:"cost,omitempty"`
}

func (o *CartShipment) GetAddress() *AddressReferenceInput {
	if o == nil {
		return nil
	}
	return o.Address
}

func (o *CartShipment) GetAddressExplicit() *AddressReferenceAddressReferenceExplicitInput {
	if v := o.GetAddress(); v != nil {
		return v.AddressReferenceAddressReferenceExplicitInput
	}
	return nil
}

func (o *CartShipment) GetAddressID() *AddressReferenceAddressReferenceID {
	if v := o.GetAddress(); v != nil {
		return v.AddressReferenceAddressReferenceID
	}
	return nil
}

func (o *CartShipment) GetCarrier() *string {
	if o == nil {
		return nil
	}
	return o.Carrier
}

func (o *CartShipment) GetCost() *Amount {
	if o == nil {
		return nil
	}
	return o.Cost
}
