// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// CreditCardNetwork - The credit card's network.
type CreditCardNetwork string

const (
	CreditCardNetworkVisa         CreditCardNetwork = "visa"
	CreditCardNetworkMastercard   CreditCardNetwork = "mastercard"
	CreditCardNetworkAmex         CreditCardNetwork = "amex"
	CreditCardNetworkDiscover     CreditCardNetwork = "discover"
	CreditCardNetworkJcb          CreditCardNetwork = "jcb"
	CreditCardNetworkUnionpay     CreditCardNetwork = "unionpay"
	CreditCardNetworkAlliancedata CreditCardNetwork = "alliancedata"
	CreditCardNetworkCitiplcc     CreditCardNetwork = "citiplcc"
)

func (e CreditCardNetwork) ToPointer() *CreditCardNetwork {
	return &e
}

func (e *CreditCardNetwork) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "visa":
		fallthrough
	case "mastercard":
		fallthrough
	case "amex":
		fallthrough
	case "discover":
		fallthrough
	case "jcb":
		fallthrough
	case "unionpay":
		fallthrough
	case "alliancedata":
		fallthrough
	case "citiplcc":
		*e = CreditCardNetwork(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreditCardNetwork: %v", v)
	}
}

type CreditCardOutput struct {
	// The expiration date, in YYYY-MM format.
	Expiration string `json:"expiration"`
	// The account number's last four digits.
	Last4 string `json:"last4"`
	// The credit card's network.
	Network CreditCardNetwork `json:"network"`
}

func (o *CreditCardOutput) GetExpiration() string {
	if o == nil {
		return ""
	}
	return o.Expiration
}

func (o *CreditCardOutput) GetLast4() string {
	if o == nil {
		return ""
	}
	return o.Last4
}

func (o *CreditCardOutput) GetNetwork() CreditCardNetwork {
	if o == nil {
		return CreditCardNetwork("")
	}
	return o.Network
}
