// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema - The address was successfully added
type Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema struct {
	Company        *string `json:"company,omitempty"`
	CountryCode    string  `json:"country_code"`
	Email          *string `json:"email,omitempty"`
	FirstName      string  `json:"first_name"`
	ID             string  `json:"id"`
	IsDefault      *bool   `json:"is_default,omitempty"`
	LastName       string  `json:"last_name"`
	Locality       string  `json:"locality"`
	Phone          *string `json:"phone,omitempty"`
	PostalCode     string  `json:"postal_code"`
	Region         *string `json:"region,omitempty"`
	StreetAddress1 string  `json:"street_address1"`
	StreetAddress2 *string `json:"street_address2,omitempty"`
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema) GetCompany() *string {
	if o == nil {
		return nil
	}
	return o.Company
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema) GetCountryCode() string {
	if o == nil {
		return ""
	}
	return o.CountryCode
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema) GetIsDefault() *bool {
	if o == nil {
		return nil
	}
	return o.IsDefault
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema) GetLocality() string {
	if o == nil {
		return ""
	}
	return o.Locality
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema) GetPhone() *string {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema) GetPostalCode() string {
	if o == nil {
		return ""
	}
	return o.PostalCode
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema) GetStreetAddress1() string {
	if o == nil {
		return ""
	}
	return o.StreetAddress1
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchema) GetStreetAddress2() *string {
	if o == nil {
		return nil
	}
	return o.StreetAddress2
}

type Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput struct {
	Company        *string `json:"company,omitempty"`
	CountryCode    string  `json:"country_code"`
	Email          *string `json:"email,omitempty"`
	FirstName      string  `json:"first_name"`
	IsDefault      *bool   `json:"is_default,omitempty"`
	LastName       string  `json:"last_name"`
	Locality       string  `json:"locality"`
	Phone          *string `json:"phone,omitempty"`
	PostalCode     string  `json:"postal_code"`
	Region         *string `json:"region,omitempty"`
	StreetAddress1 string  `json:"street_address1"`
	StreetAddress2 *string `json:"street_address2,omitempty"`
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput) GetCompany() *string {
	if o == nil {
		return nil
	}
	return o.Company
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput) GetCountryCode() string {
	if o == nil {
		return ""
	}
	return o.CountryCode
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput) GetFirstName() string {
	if o == nil {
		return ""
	}
	return o.FirstName
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput) GetIsDefault() *bool {
	if o == nil {
		return nil
	}
	return o.IsDefault
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput) GetLastName() string {
	if o == nil {
		return ""
	}
	return o.LastName
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput) GetLocality() string {
	if o == nil {
		return ""
	}
	return o.Locality
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput) GetPhone() *string {
	if o == nil {
		return nil
	}
	return o.Phone
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput) GetPostalCode() string {
	if o == nil {
		return ""
	}
	return o.PostalCode
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput) GetStreetAddress1() string {
	if o == nil {
		return ""
	}
	return o.StreetAddress1
}

func (o *Oneaccount1addressesPostRequestBodyContentApplication1jsonSchemaInput) GetStreetAddress2() *string {
	if o == nil {
		return nil
	}
	return o.StreetAddress2
}
