// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork - The credit card network.
type Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork string

const (
	Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetworkVisa         Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork = "visa"
	Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetworkMastercard   Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork = "mastercard"
	Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetworkAmex         Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork = "amex"
	Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetworkDiscover     Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork = "discover"
	Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetworkJcb          Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork = "jcb"
	Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetworkUnionpay     Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork = "unionpay"
	Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetworkAlliancedata Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork = "alliancedata"
	Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetworkCitiplcc     Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork = "citiplcc"
)

func (e Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork) ToPointer() *Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork {
	return &e
}

func (e *Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "visa":
		fallthrough
	case "mastercard":
		fallthrough
	case "amex":
		fallthrough
	case "discover":
		fallthrough
	case "jcb":
		fallthrough
	case "unionpay":
		fallthrough
	case "alliancedata":
		fallthrough
	case "citiplcc":
		*e = Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork: %v", v)
	}
}

// Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaType - Credit card type
type Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaType string

const (
	Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaTypeCredit Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaType = "credit"
	Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaTypePlcc   Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaType = "plcc"
)

func (e Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaType) ToPointer() *Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaType {
	return &e
}

func (e *Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "credit":
		fallthrough
	case "plcc":
		*e = Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaType: %v", v)
	}
}

// Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaOutput - The payment method was successfully added
type Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaOutput struct {
	// The ID of credit card's billing address
	BillingAddressID *string `json:"billing_address_id,omitempty"`
	// The Bank Identification Number for the credit card. This is typically the first 4-6 digits of the credit card number.
	Bin string `json:"bin"`
	// The expiration date of the credit card. TODO TO MAKE EXPIRATION REUSABLE
	Expiration string  `json:"expiration"`
	ID         *string `json:"id,omitempty"`
	// The last 4 digits of the credit card number.
	Last4 string `json:"last4"`
	// The credit card network.
	Network Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork `json:"network"`
	// The Bolt token associated to the credit card.
	Token string `json:"token"`
	// Credit card type
	Type Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaType `json:"type"`
}

func (o *Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaOutput) GetBillingAddressID() *string {
	if o == nil {
		return nil
	}
	return o.BillingAddressID
}

func (o *Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaOutput) GetBin() string {
	if o == nil {
		return ""
	}
	return o.Bin
}

func (o *Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaOutput) GetExpiration() string {
	if o == nil {
		return ""
	}
	return o.Expiration
}

func (o *Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaOutput) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaOutput) GetLast4() string {
	if o == nil {
		return ""
	}
	return o.Last4
}

func (o *Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaOutput) GetNetwork() Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork {
	if o == nil {
		return Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaNetwork("")
	}
	return o.Network
}

func (o *Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaOutput) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

func (o *Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaOutput) GetType() Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaType {
	if o == nil {
		return Oneaccount1paymentMethodsPostRequestBodyContentApplication1jsonSchemaType("")
	}
	return o.Type
}
