// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type OnepaymentsPostResponses200ContentApplication1jsonSchemaActionMethod string

const (
	OnepaymentsPostResponses200ContentApplication1jsonSchemaActionMethodGet  OnepaymentsPostResponses200ContentApplication1jsonSchemaActionMethod = "GET"
	OnepaymentsPostResponses200ContentApplication1jsonSchemaActionMethodPost OnepaymentsPostResponses200ContentApplication1jsonSchemaActionMethod = "POST"
)

func (e OnepaymentsPostResponses200ContentApplication1jsonSchemaActionMethod) ToPointer() *OnepaymentsPostResponses200ContentApplication1jsonSchemaActionMethod {
	return &e
}

func (e *OnepaymentsPostResponses200ContentApplication1jsonSchemaActionMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "GET":
		fallthrough
	case "POST":
		*e = OnepaymentsPostResponses200ContentApplication1jsonSchemaActionMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OnepaymentsPostResponses200ContentApplication1jsonSchemaActionMethod: %v", v)
	}
}

type OnepaymentsPostResponses200ContentApplication1jsonSchemaActionType string

const (
	OnepaymentsPostResponses200ContentApplication1jsonSchemaActionTypeRedirect OnepaymentsPostResponses200ContentApplication1jsonSchemaActionType = "redirect"
	OnepaymentsPostResponses200ContentApplication1jsonSchemaActionTypeFinalize OnepaymentsPostResponses200ContentApplication1jsonSchemaActionType = "finalize"
)

func (e OnepaymentsPostResponses200ContentApplication1jsonSchemaActionType) ToPointer() *OnepaymentsPostResponses200ContentApplication1jsonSchemaActionType {
	return &e
}

func (e *OnepaymentsPostResponses200ContentApplication1jsonSchemaActionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "redirect":
		fallthrough
	case "finalize":
		*e = OnepaymentsPostResponses200ContentApplication1jsonSchemaActionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OnepaymentsPostResponses200ContentApplication1jsonSchemaActionType: %v", v)
	}
}

type OnepaymentsPostResponses200ContentApplication1jsonSchemaAction struct {
	Method *OnepaymentsPostResponses200ContentApplication1jsonSchemaActionMethod `json:"method,omitempty"`
	Type   *OnepaymentsPostResponses200ContentApplication1jsonSchemaActionType   `json:"type,omitempty"`
	URL    *string                                                               `json:"url,omitempty"`
}

func (o *OnepaymentsPostResponses200ContentApplication1jsonSchemaAction) GetMethod() *OnepaymentsPostResponses200ContentApplication1jsonSchemaActionMethod {
	if o == nil {
		return nil
	}
	return o.Method
}

func (o *OnepaymentsPostResponses200ContentApplication1jsonSchemaAction) GetType() *OnepaymentsPostResponses200ContentApplication1jsonSchemaActionType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *OnepaymentsPostResponses200ContentApplication1jsonSchemaAction) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

type OnepaymentsPostResponses200ContentApplication1jsonSchemaStatus string

const (
	OnepaymentsPostResponses200ContentApplication1jsonSchemaStatusAwaitingUserConfirmation OnepaymentsPostResponses200ContentApplication1jsonSchemaStatus = "awaiting_user_confirmation"
	OnepaymentsPostResponses200ContentApplication1jsonSchemaStatusPaymentReady             OnepaymentsPostResponses200ContentApplication1jsonSchemaStatus = "payment_ready"
	OnepaymentsPostResponses200ContentApplication1jsonSchemaStatusUpdatePaymentMethod      OnepaymentsPostResponses200ContentApplication1jsonSchemaStatus = "update_payment_method"
	OnepaymentsPostResponses200ContentApplication1jsonSchemaStatusSuccess                  OnepaymentsPostResponses200ContentApplication1jsonSchemaStatus = "success"
)

func (e OnepaymentsPostResponses200ContentApplication1jsonSchemaStatus) ToPointer() *OnepaymentsPostResponses200ContentApplication1jsonSchemaStatus {
	return &e
}

func (e *OnepaymentsPostResponses200ContentApplication1jsonSchemaStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "awaiting_user_confirmation":
		fallthrough
	case "payment_ready":
		fallthrough
	case "update_payment_method":
		fallthrough
	case "success":
		*e = OnepaymentsPostResponses200ContentApplication1jsonSchemaStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OnepaymentsPostResponses200ContentApplication1jsonSchemaStatus: %v", v)
	}
}

// OnepaymentsPostResponses200ContentApplication1jsonSchema - Payment token retrieved
type OnepaymentsPostResponses200ContentApplication1jsonSchema struct {
	Action *OnepaymentsPostResponses200ContentApplication1jsonSchemaAction `json:"action,omitempty"`
	ID     *string                                                         `json:"id,omitempty"`
	Status *OnepaymentsPostResponses200ContentApplication1jsonSchemaStatus `json:"status,omitempty"`
}

func (o *OnepaymentsPostResponses200ContentApplication1jsonSchema) GetAction() *OnepaymentsPostResponses200ContentApplication1jsonSchemaAction {
	if o == nil {
		return nil
	}
	return o.Action
}

func (o *OnepaymentsPostResponses200ContentApplication1jsonSchema) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *OnepaymentsPostResponses200ContentApplication1jsonSchema) GetStatus() *OnepaymentsPostResponses200ContentApplication1jsonSchemaStatus {
	if o == nil {
		return nil
	}
	return o.Status
}
