// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/speakeasy-sdks/bolt-alpha-spec/pkg/utils"
)

type OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartAmounts struct {
	Currency string `json:"currency"`
	// The total tax amount, in cents for all of the items associated with the cart.
	Tax *int64 `json:"tax,omitempty"`
	// The total amount, in cents, including its items and taxes (if applicable).
	Total int64 `json:"total"`
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartAmounts) GetCurrency() string {
	if o == nil {
		return ""
	}
	return o.Currency
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartAmounts) GetTax() *int64 {
	if o == nil {
		return nil
	}
	return o.Tax
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartAmounts) GetTotal() int64 {
	if o == nil {
		return 0
	}
	return o.Total
}

type OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartDiscounts struct {
	Amounts OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartPropertiesAmounts `json:"amounts"`
	// Discount code.
	Code *string `json:"code,omitempty"`
	// Used to provide a link to additional details, such as a landing page, associated with the discount offering.
	DetailsURL *string `json:"details_url,omitempty"`
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartDiscounts) GetAmounts() OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartPropertiesAmounts {
	if o == nil {
		return OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartPropertiesAmounts{}
	}
	return o.Amounts
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartDiscounts) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartDiscounts) GetDetailsURL() *string {
	if o == nil {
		return nil
	}
	return o.DetailsURL
}

type OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartItems struct {
	// A human-readable description of this cart item.
	Description *string `json:"description,omitempty"`
	// Used to provide a link to the image associated with the item.
	ImageURL *string `json:"image_url,omitempty"`
	// The name of a given item.
	Name string `json:"name"`
	// The number of units that comprise this cart item.
	Quantity int64 `json:"quantity"`
	// This value is used by Bolt as an external reference to a given item.
	Reference string `json:"reference"`
	// The total amount, in cents, of the item including its taxes if applicable.
	TotalAmount int64 `json:"total_amount"`
	// The price of one unit of the item; for example, the price of one pack of socks.
	UnitPrice int64 `json:"unit_price"`
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartItems) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartItems) GetImageURL() *string {
	if o == nil {
		return nil
	}
	return o.ImageURL
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartItems) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartItems) GetQuantity() int64 {
	if o == nil {
		return 0
	}
	return o.Quantity
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartItems) GetReference() string {
	if o == nil {
		return ""
	}
	return o.Reference
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartItems) GetTotalAmount() int64 {
	if o == nil {
		return 0
	}
	return o.TotalAmount
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartItems) GetUnitPrice() int64 {
	if o == nil {
		return 0
	}
	return o.UnitPrice
}

type OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInputType string

const (
	OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInputTypeExplicit OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInputType = "explicit"
	OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInputTypeID       OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInputType = "id"
)

type OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInput struct {
	AddressID            *AddressID
	AddressExplicitInput *AddressExplicitInput

	Type OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInputType
}

func CreateOnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInputExplicit(explicit AddressExplicitInput) OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInput {
	typ := OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInputTypeExplicit
	typStr := string(typ)
	explicit.DotTag = typStr

	return OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInput{
		AddressExplicitInput: &explicit,
		Type:                 typ,
	}
}

func CreateOnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInputID(id AddressID) OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInput {
	typ := OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInputTypeID
	typStr := string(typ)
	id.DotTag = typStr

	return OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInput{
		AddressID: &id,
		Type:      typ,
	}
}

func (u *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInput) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		DotTag string
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.DotTag {
	case "explicit":
		addressExplicitInput := new(AddressExplicitInput)
		if err := utils.UnmarshalJSON(data, &addressExplicitInput, "", true, true); err != nil {
			return fmt.Errorf("could not unmarshal expected type: %w", err)
		}

		u.AddressExplicitInput = addressExplicitInput
		u.Type = OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInputTypeExplicit
		return nil
	case "id":
		addressID := new(AddressID)
		if err := utils.UnmarshalJSON(data, &addressID, "", true, true); err != nil {
			return fmt.Errorf("could not unmarshal expected type: %w", err)
		}

		u.AddressID = addressID
		u.Type = OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInputTypeID
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInput) MarshalJSON() ([]byte, error) {
	if u.AddressID != nil {
		return utils.MarshalJSON(u.AddressID, "", true)
	}

	if u.AddressExplicitInput != nil {
		return utils.MarshalJSON(u.AddressExplicitInput, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

type OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipments struct {
	// The Address object is used for shipping, and physical store address use cases.
	Address *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInput `json:"address,omitempty"`
	// The name of the carrier selected.
	Carrier *string                                                                                 `json:"carrier,omitempty"`
	Cost    *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartPropertiesAmounts `json:"cost,omitempty"`
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipments) GetAddress() *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipmentsAddressInput {
	if o == nil {
		return nil
	}
	return o.Address
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipments) GetAddressExplicit() *AddressExplicitInput {
	if v := o.GetAddress(); v != nil {
		return v.AddressExplicitInput
	}
	return nil
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipments) GetAddressID() *AddressID {
	if v := o.GetAddress(); v != nil {
		return v.AddressID
	}
	return nil
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipments) GetCarrier() *string {
	if o == nil {
		return nil
	}
	return o.Carrier
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipments) GetCost() *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartPropertiesAmounts {
	if o == nil {
		return nil
	}
	return o.Cost
}

type OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCart struct {
	Amounts   OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartAmounts     `json:"amounts"`
	Discounts []OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartDiscounts `json:"discounts,omitempty"`
	// This field corresponds to the merchant's order reference associated with this Bolt transaction.
	DisplayID *string                                                                      `json:"display_id,omitempty"`
	Items     []OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartItems `json:"items,omitempty"`
	// Used optionally to pass additional information like order numbers or other IDs as needed.
	OrderDescription *string `json:"order_description,omitempty"`
	// This value is used by Bolt as an external reference to a given order. This reference must be unique per successful transaction.
	OrderReference string                                                                           `json:"order_reference"`
	Shipments      []OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipments `json:"shipments,omitempty"`
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCart) GetAmounts() OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartAmounts {
	if o == nil {
		return OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartAmounts{}
	}
	return o.Amounts
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCart) GetDiscounts() []OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartDiscounts {
	if o == nil {
		return nil
	}
	return o.Discounts
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCart) GetDisplayID() *string {
	if o == nil {
		return nil
	}
	return o.DisplayID
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCart) GetItems() []OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartItems {
	if o == nil {
		return nil
	}
	return o.Items
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCart) GetOrderDescription() *string {
	if o == nil {
		return nil
	}
	return o.OrderDescription
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCart) GetOrderReference() string {
	if o == nil {
		return ""
	}
	return o.OrderReference
}

func (o *OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCart) GetShipments() []OnepaymentsPostRequestBodyContentApplication1jsonSchemaPropertiesCartShipments {
	if o == nil {
		return nil
	}
	return o.Shipments
}
