// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PaymentInitializeRequest struct {
	Cart          Cart                   `json:"cart"`
	PaymentMethod PaymentMethodReference `json:"payment_method"`
}

func (o *PaymentInitializeRequest) GetCart() Cart {
	if o == nil {
		return Cart{}
	}
	return o.Cart
}

func (o *PaymentInitializeRequest) GetPaymentMethod() PaymentMethodReference {
	if o == nil {
		return PaymentMethodReference{}
	}
	return o.PaymentMethod
}
